// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partner_api2.proto

package com.emporiaenergy.partnerapi2;

public interface AuthenticationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:emporiaenergy.partner_api_2.AuthenticationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * the authorization token that you need to include with all other calls to the API
   * </pre>
   *
   * <code>string auth_token = 1;</code>
   * @return The authToken.
   */
  java.lang.String getAuthToken();
  /**
   * <pre>
   * the authorization token that you need to include with all other calls to the API
   * </pre>
   *
   * <code>string auth_token = 1;</code>
   * @return The bytes for authToken.
   */
  com.google.protobuf.ByteString
      getAuthTokenBytes();
}
