// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partner_api2.proto

package com.emporiaenergy.partnerapi2;

public interface BatteriesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:emporiaenergy.partner_api_2.BatteriesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .emporiaenergy.partner_api_2.Battery batteries = 1;</code>
   */
  java.util.List<com.emporiaenergy.partnerapi2.Battery> 
      getBatteriesList();
  /**
   * <code>repeated .emporiaenergy.partner_api_2.Battery batteries = 1;</code>
   */
  com.emporiaenergy.partnerapi2.Battery getBatteries(int index);
  /**
   * <code>repeated .emporiaenergy.partner_api_2.Battery batteries = 1;</code>
   */
  int getBatteriesCount();
  /**
   * <code>repeated .emporiaenergy.partner_api_2.Battery batteries = 1;</code>
   */
  java.util.List<? extends com.emporiaenergy.partnerapi2.BatteryOrBuilder> 
      getBatteriesOrBuilderList();
  /**
   * <code>repeated .emporiaenergy.partner_api_2.Battery batteries = 1;</code>
   */
  com.emporiaenergy.partnerapi2.BatteryOrBuilder getBatteriesOrBuilder(
      int index);
}
