// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partner_api2.proto

package com.emporiaenergy.partnerapi2;

/**
 * Protobuf type {@code emporiaenergy.partner_api_2.BatteriesResponse}
 */
public final class BatteriesResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:emporiaenergy.partner_api_2.BatteriesResponse)
    BatteriesResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BatteriesResponse.newBuilder() to construct.
  private BatteriesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BatteriesResponse() {
    batteries_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BatteriesResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BatteriesResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              batteries_ = new java.util.ArrayList<com.emporiaenergy.partnerapi2.Battery>();
              mutable_bitField0_ |= 0x00000001;
            }
            batteries_.add(
                input.readMessage(com.emporiaenergy.partnerapi2.Battery.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        batteries_ = java.util.Collections.unmodifiableList(batteries_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.emporiaenergy.partnerapi2.PartnerApi2.internal_static_emporiaenergy_partner_api_2_BatteriesResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.emporiaenergy.partnerapi2.PartnerApi2.internal_static_emporiaenergy_partner_api_2_BatteriesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.emporiaenergy.partnerapi2.BatteriesResponse.class, com.emporiaenergy.partnerapi2.BatteriesResponse.Builder.class);
  }

  public static final int BATTERIES_FIELD_NUMBER = 1;
  private java.util.List<com.emporiaenergy.partnerapi2.Battery> batteries_;
  /**
   * <code>repeated .emporiaenergy.partner_api_2.Battery batteries = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.emporiaenergy.partnerapi2.Battery> getBatteriesList() {
    return batteries_;
  }
  /**
   * <code>repeated .emporiaenergy.partner_api_2.Battery batteries = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.emporiaenergy.partnerapi2.BatteryOrBuilder> 
      getBatteriesOrBuilderList() {
    return batteries_;
  }
  /**
   * <code>repeated .emporiaenergy.partner_api_2.Battery batteries = 1;</code>
   */
  @java.lang.Override
  public int getBatteriesCount() {
    return batteries_.size();
  }
  /**
   * <code>repeated .emporiaenergy.partner_api_2.Battery batteries = 1;</code>
   */
  @java.lang.Override
  public com.emporiaenergy.partnerapi2.Battery getBatteries(int index) {
    return batteries_.get(index);
  }
  /**
   * <code>repeated .emporiaenergy.partner_api_2.Battery batteries = 1;</code>
   */
  @java.lang.Override
  public com.emporiaenergy.partnerapi2.BatteryOrBuilder getBatteriesOrBuilder(
      int index) {
    return batteries_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < batteries_.size(); i++) {
      output.writeMessage(1, batteries_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < batteries_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, batteries_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.emporiaenergy.partnerapi2.BatteriesResponse)) {
      return super.equals(obj);
    }
    com.emporiaenergy.partnerapi2.BatteriesResponse other = (com.emporiaenergy.partnerapi2.BatteriesResponse) obj;

    if (!getBatteriesList()
        .equals(other.getBatteriesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getBatteriesCount() > 0) {
      hash = (37 * hash) + BATTERIES_FIELD_NUMBER;
      hash = (53 * hash) + getBatteriesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.emporiaenergy.partnerapi2.BatteriesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.emporiaenergy.partnerapi2.BatteriesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.emporiaenergy.partnerapi2.BatteriesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.emporiaenergy.partnerapi2.BatteriesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.emporiaenergy.partnerapi2.BatteriesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.emporiaenergy.partnerapi2.BatteriesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.emporiaenergy.partnerapi2.BatteriesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.emporiaenergy.partnerapi2.BatteriesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.emporiaenergy.partnerapi2.BatteriesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.emporiaenergy.partnerapi2.BatteriesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.emporiaenergy.partnerapi2.BatteriesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.emporiaenergy.partnerapi2.BatteriesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.emporiaenergy.partnerapi2.BatteriesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code emporiaenergy.partner_api_2.BatteriesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:emporiaenergy.partner_api_2.BatteriesResponse)
      com.emporiaenergy.partnerapi2.BatteriesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.emporiaenergy.partnerapi2.PartnerApi2.internal_static_emporiaenergy_partner_api_2_BatteriesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.emporiaenergy.partnerapi2.PartnerApi2.internal_static_emporiaenergy_partner_api_2_BatteriesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.emporiaenergy.partnerapi2.BatteriesResponse.class, com.emporiaenergy.partnerapi2.BatteriesResponse.Builder.class);
    }

    // Construct using com.emporiaenergy.partnerapi2.BatteriesResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBatteriesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (batteriesBuilder_ == null) {
        batteries_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        batteriesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.emporiaenergy.partnerapi2.PartnerApi2.internal_static_emporiaenergy_partner_api_2_BatteriesResponse_descriptor;
    }

    @java.lang.Override
    public com.emporiaenergy.partnerapi2.BatteriesResponse getDefaultInstanceForType() {
      return com.emporiaenergy.partnerapi2.BatteriesResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.emporiaenergy.partnerapi2.BatteriesResponse build() {
      com.emporiaenergy.partnerapi2.BatteriesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.emporiaenergy.partnerapi2.BatteriesResponse buildPartial() {
      com.emporiaenergy.partnerapi2.BatteriesResponse result = new com.emporiaenergy.partnerapi2.BatteriesResponse(this);
      int from_bitField0_ = bitField0_;
      if (batteriesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          batteries_ = java.util.Collections.unmodifiableList(batteries_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.batteries_ = batteries_;
      } else {
        result.batteries_ = batteriesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.emporiaenergy.partnerapi2.BatteriesResponse) {
        return mergeFrom((com.emporiaenergy.partnerapi2.BatteriesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.emporiaenergy.partnerapi2.BatteriesResponse other) {
      if (other == com.emporiaenergy.partnerapi2.BatteriesResponse.getDefaultInstance()) return this;
      if (batteriesBuilder_ == null) {
        if (!other.batteries_.isEmpty()) {
          if (batteries_.isEmpty()) {
            batteries_ = other.batteries_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureBatteriesIsMutable();
            batteries_.addAll(other.batteries_);
          }
          onChanged();
        }
      } else {
        if (!other.batteries_.isEmpty()) {
          if (batteriesBuilder_.isEmpty()) {
            batteriesBuilder_.dispose();
            batteriesBuilder_ = null;
            batteries_ = other.batteries_;
            bitField0_ = (bitField0_ & ~0x00000001);
            batteriesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBatteriesFieldBuilder() : null;
          } else {
            batteriesBuilder_.addAllMessages(other.batteries_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.emporiaenergy.partnerapi2.BatteriesResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.emporiaenergy.partnerapi2.BatteriesResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.emporiaenergy.partnerapi2.Battery> batteries_ =
      java.util.Collections.emptyList();
    private void ensureBatteriesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        batteries_ = new java.util.ArrayList<com.emporiaenergy.partnerapi2.Battery>(batteries_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.emporiaenergy.partnerapi2.Battery, com.emporiaenergy.partnerapi2.Battery.Builder, com.emporiaenergy.partnerapi2.BatteryOrBuilder> batteriesBuilder_;

    /**
     * <code>repeated .emporiaenergy.partner_api_2.Battery batteries = 1;</code>
     */
    public java.util.List<com.emporiaenergy.partnerapi2.Battery> getBatteriesList() {
      if (batteriesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(batteries_);
      } else {
        return batteriesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .emporiaenergy.partner_api_2.Battery batteries = 1;</code>
     */
    public int getBatteriesCount() {
      if (batteriesBuilder_ == null) {
        return batteries_.size();
      } else {
        return batteriesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .emporiaenergy.partner_api_2.Battery batteries = 1;</code>
     */
    public com.emporiaenergy.partnerapi2.Battery getBatteries(int index) {
      if (batteriesBuilder_ == null) {
        return batteries_.get(index);
      } else {
        return batteriesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .emporiaenergy.partner_api_2.Battery batteries = 1;</code>
     */
    public Builder setBatteries(
        int index, com.emporiaenergy.partnerapi2.Battery value) {
      if (batteriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBatteriesIsMutable();
        batteries_.set(index, value);
        onChanged();
      } else {
        batteriesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .emporiaenergy.partner_api_2.Battery batteries = 1;</code>
     */
    public Builder setBatteries(
        int index, com.emporiaenergy.partnerapi2.Battery.Builder builderForValue) {
      if (batteriesBuilder_ == null) {
        ensureBatteriesIsMutable();
        batteries_.set(index, builderForValue.build());
        onChanged();
      } else {
        batteriesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .emporiaenergy.partner_api_2.Battery batteries = 1;</code>
     */
    public Builder addBatteries(com.emporiaenergy.partnerapi2.Battery value) {
      if (batteriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBatteriesIsMutable();
        batteries_.add(value);
        onChanged();
      } else {
        batteriesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .emporiaenergy.partner_api_2.Battery batteries = 1;</code>
     */
    public Builder addBatteries(
        int index, com.emporiaenergy.partnerapi2.Battery value) {
      if (batteriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBatteriesIsMutable();
        batteries_.add(index, value);
        onChanged();
      } else {
        batteriesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .emporiaenergy.partner_api_2.Battery batteries = 1;</code>
     */
    public Builder addBatteries(
        com.emporiaenergy.partnerapi2.Battery.Builder builderForValue) {
      if (batteriesBuilder_ == null) {
        ensureBatteriesIsMutable();
        batteries_.add(builderForValue.build());
        onChanged();
      } else {
        batteriesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .emporiaenergy.partner_api_2.Battery batteries = 1;</code>
     */
    public Builder addBatteries(
        int index, com.emporiaenergy.partnerapi2.Battery.Builder builderForValue) {
      if (batteriesBuilder_ == null) {
        ensureBatteriesIsMutable();
        batteries_.add(index, builderForValue.build());
        onChanged();
      } else {
        batteriesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .emporiaenergy.partner_api_2.Battery batteries = 1;</code>
     */
    public Builder addAllBatteries(
        java.lang.Iterable<? extends com.emporiaenergy.partnerapi2.Battery> values) {
      if (batteriesBuilder_ == null) {
        ensureBatteriesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, batteries_);
        onChanged();
      } else {
        batteriesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .emporiaenergy.partner_api_2.Battery batteries = 1;</code>
     */
    public Builder clearBatteries() {
      if (batteriesBuilder_ == null) {
        batteries_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        batteriesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .emporiaenergy.partner_api_2.Battery batteries = 1;</code>
     */
    public Builder removeBatteries(int index) {
      if (batteriesBuilder_ == null) {
        ensureBatteriesIsMutable();
        batteries_.remove(index);
        onChanged();
      } else {
        batteriesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .emporiaenergy.partner_api_2.Battery batteries = 1;</code>
     */
    public com.emporiaenergy.partnerapi2.Battery.Builder getBatteriesBuilder(
        int index) {
      return getBatteriesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .emporiaenergy.partner_api_2.Battery batteries = 1;</code>
     */
    public com.emporiaenergy.partnerapi2.BatteryOrBuilder getBatteriesOrBuilder(
        int index) {
      if (batteriesBuilder_ == null) {
        return batteries_.get(index);  } else {
        return batteriesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .emporiaenergy.partner_api_2.Battery batteries = 1;</code>
     */
    public java.util.List<? extends com.emporiaenergy.partnerapi2.BatteryOrBuilder> 
         getBatteriesOrBuilderList() {
      if (batteriesBuilder_ != null) {
        return batteriesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(batteries_);
      }
    }
    /**
     * <code>repeated .emporiaenergy.partner_api_2.Battery batteries = 1;</code>
     */
    public com.emporiaenergy.partnerapi2.Battery.Builder addBatteriesBuilder() {
      return getBatteriesFieldBuilder().addBuilder(
          com.emporiaenergy.partnerapi2.Battery.getDefaultInstance());
    }
    /**
     * <code>repeated .emporiaenergy.partner_api_2.Battery batteries = 1;</code>
     */
    public com.emporiaenergy.partnerapi2.Battery.Builder addBatteriesBuilder(
        int index) {
      return getBatteriesFieldBuilder().addBuilder(
          index, com.emporiaenergy.partnerapi2.Battery.getDefaultInstance());
    }
    /**
     * <code>repeated .emporiaenergy.partner_api_2.Battery batteries = 1;</code>
     */
    public java.util.List<com.emporiaenergy.partnerapi2.Battery.Builder> 
         getBatteriesBuilderList() {
      return getBatteriesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.emporiaenergy.partnerapi2.Battery, com.emporiaenergy.partnerapi2.Battery.Builder, com.emporiaenergy.partnerapi2.BatteryOrBuilder> 
        getBatteriesFieldBuilder() {
      if (batteriesBuilder_ == null) {
        batteriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.emporiaenergy.partnerapi2.Battery, com.emporiaenergy.partnerapi2.Battery.Builder, com.emporiaenergy.partnerapi2.BatteryOrBuilder>(
                batteries_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        batteries_ = null;
      }
      return batteriesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:emporiaenergy.partner_api_2.BatteriesResponse)
  }

  // @@protoc_insertion_point(class_scope:emporiaenergy.partner_api_2.BatteriesResponse)
  private static final com.emporiaenergy.partnerapi2.BatteriesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.emporiaenergy.partnerapi2.BatteriesResponse();
  }

  public static com.emporiaenergy.partnerapi2.BatteriesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BatteriesResponse>
      PARSER = new com.google.protobuf.AbstractParser<BatteriesResponse>() {
    @java.lang.Override
    public BatteriesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BatteriesResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BatteriesResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BatteriesResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.emporiaenergy.partnerapi2.BatteriesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

