// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partner_api2.proto

package com.emporiaenergy.partnerapi2;

public interface BatterySettingsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:emporiaenergy.partner_api_2.BatterySettings)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * identifies this device 
   * </pre>
   *
   * <code>string manufacturer_device_id = 1;</code>
   * @return The manufacturerDeviceId.
   */
  java.lang.String getManufacturerDeviceId();
  /**
   * <pre>
   * identifies this device 
   * </pre>
   *
   * <code>string manufacturer_device_id = 1;</code>
   * @return The bytes for manufacturerDeviceId.
   */
  com.google.protobuf.ByteString
      getManufacturerDeviceIdBytes();

  /**
   * <pre>
   * the battery capacity to reserve, the battery will not discharge below this level; 1 to 100 (inclusive)
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue reserve_soc_percentage = 2;</code>
   * @return Whether the reserveSocPercentage field is set.
   */
  boolean hasReserveSocPercentage();
  /**
   * <pre>
   * the battery capacity to reserve, the battery will not discharge below this level; 1 to 100 (inclusive)
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue reserve_soc_percentage = 2;</code>
   * @return The reserveSocPercentage.
   */
  com.google.protobuf.DoubleValue getReserveSocPercentage();
  /**
   * <pre>
   * the battery capacity to reserve, the battery will not discharge below this level; 1 to 100 (inclusive)
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue reserve_soc_percentage = 2;</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getReserveSocPercentageOrBuilder();

  /**
   * <code>.emporiaenergy.partner_api_2.BatterySettings.LoadFollowing load_following = 10;</code>
   * @return Whether the loadFollowing field is set.
   */
  boolean hasLoadFollowing();
  /**
   * <code>.emporiaenergy.partner_api_2.BatterySettings.LoadFollowing load_following = 10;</code>
   * @return The loadFollowing.
   */
  com.emporiaenergy.partnerapi2.BatterySettings.LoadFollowing getLoadFollowing();
  /**
   * <code>.emporiaenergy.partner_api_2.BatterySettings.LoadFollowing load_following = 10;</code>
   */
  com.emporiaenergy.partnerapi2.BatterySettings.LoadFollowingOrBuilder getLoadFollowingOrBuilder();

  /**
   * <code>.emporiaenergy.partner_api_2.BatterySettings.ChargeWithExcessSolar charge_with_excess_solar = 11;</code>
   * @return Whether the chargeWithExcessSolar field is set.
   */
  boolean hasChargeWithExcessSolar();
  /**
   * <code>.emporiaenergy.partner_api_2.BatterySettings.ChargeWithExcessSolar charge_with_excess_solar = 11;</code>
   * @return The chargeWithExcessSolar.
   */
  com.emporiaenergy.partnerapi2.BatterySettings.ChargeWithExcessSolar getChargeWithExcessSolar();
  /**
   * <code>.emporiaenergy.partner_api_2.BatterySettings.ChargeWithExcessSolar charge_with_excess_solar = 11;</code>
   */
  com.emporiaenergy.partnerapi2.BatterySettings.ChargeWithExcessSolarOrBuilder getChargeWithExcessSolarOrBuilder();

  /**
   * <code>.emporiaenergy.partner_api_2.BatterySettings.ChargeToStateOfCharge charge_to_state_of_charge = 12;</code>
   * @return Whether the chargeToStateOfCharge field is set.
   */
  boolean hasChargeToStateOfCharge();
  /**
   * <code>.emporiaenergy.partner_api_2.BatterySettings.ChargeToStateOfCharge charge_to_state_of_charge = 12;</code>
   * @return The chargeToStateOfCharge.
   */
  com.emporiaenergy.partnerapi2.BatterySettings.ChargeToStateOfCharge getChargeToStateOfCharge();
  /**
   * <code>.emporiaenergy.partner_api_2.BatterySettings.ChargeToStateOfCharge charge_to_state_of_charge = 12;</code>
   */
  com.emporiaenergy.partnerapi2.BatterySettings.ChargeToStateOfChargeOrBuilder getChargeToStateOfChargeOrBuilder();

  /**
   * <code>.emporiaenergy.partner_api_2.BatterySettings.DischargeToStateOfCharge discharge_to_state_of_charge = 13;</code>
   * @return Whether the dischargeToStateOfCharge field is set.
   */
  boolean hasDischargeToStateOfCharge();
  /**
   * <code>.emporiaenergy.partner_api_2.BatterySettings.DischargeToStateOfCharge discharge_to_state_of_charge = 13;</code>
   * @return The dischargeToStateOfCharge.
   */
  com.emporiaenergy.partnerapi2.BatterySettings.DischargeToStateOfCharge getDischargeToStateOfCharge();
  /**
   * <code>.emporiaenergy.partner_api_2.BatterySettings.DischargeToStateOfCharge discharge_to_state_of_charge = 13;</code>
   */
  com.emporiaenergy.partnerapi2.BatterySettings.DischargeToStateOfChargeOrBuilder getDischargeToStateOfChargeOrBuilder();

  /**
   * <code>.emporiaenergy.partner_api_2.BatterySettings.Idle idle = 14;</code>
   * @return Whether the idle field is set.
   */
  boolean hasIdle();
  /**
   * <code>.emporiaenergy.partner_api_2.BatterySettings.Idle idle = 14;</code>
   * @return The idle.
   */
  com.emporiaenergy.partnerapi2.BatterySettings.Idle getIdle();
  /**
   * <code>.emporiaenergy.partner_api_2.BatterySettings.Idle idle = 14;</code>
   */
  com.emporiaenergy.partnerapi2.BatterySettings.IdleOrBuilder getIdleOrBuilder();

  public com.emporiaenergy.partnerapi2.BatterySettings.DispatchModeCase getDispatchModeCase();
}
