// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partner_api2.proto

package com.emporiaenergy.partnerapi2;

public interface BatteryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:emporiaenergy.partner_api_2.Battery)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * the maximum capacity of the battery in kilowatt-hours
   * </pre>
   *
   * <code>double capacity_kwhs = 1;</code>
   * @return The capacityKwhs.
   */
  double getCapacityKwhs();

  /**
   * <pre>
   * the maximum power of the inverter in kWatts
   * </pre>
   *
   * <code>double inverter_max_power_kwatts = 2;</code>
   * @return The inverterMaxPowerKwatts.
   */
  double getInverterMaxPowerKwatts();

  /**
   * <pre>
   * the current State of Charge of the battery, as a percentage 1 to 100 (inclusive) 
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue soc_percentage = 3;</code>
   * @return Whether the socPercentage field is set.
   */
  boolean hasSocPercentage();
  /**
   * <pre>
   * the current State of Charge of the battery, as a percentage 1 to 100 (inclusive) 
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue soc_percentage = 3;</code>
   * @return The socPercentage.
   */
  com.google.protobuf.DoubleValue getSocPercentage();
  /**
   * <pre>
   * the current State of Charge of the battery, as a percentage 1 to 100 (inclusive) 
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue soc_percentage = 3;</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getSocPercentageOrBuilder();

  /**
   * <pre>
   * the settings that may be changed using the API, starting at a higher index to leave room for additional non-changeable fields
   * </pre>
   *
   * <code>.emporiaenergy.partner_api_2.BatterySettings settings = 10;</code>
   * @return Whether the settings field is set.
   */
  boolean hasSettings();
  /**
   * <pre>
   * the settings that may be changed using the API, starting at a higher index to leave room for additional non-changeable fields
   * </pre>
   *
   * <code>.emporiaenergy.partner_api_2.BatterySettings settings = 10;</code>
   * @return The settings.
   */
  com.emporiaenergy.partnerapi2.BatterySettings getSettings();
  /**
   * <pre>
   * the settings that may be changed using the API, starting at a higher index to leave room for additional non-changeable fields
   * </pre>
   *
   * <code>.emporiaenergy.partner_api_2.BatterySettings settings = 10;</code>
   */
  com.emporiaenergy.partnerapi2.BatterySettingsOrBuilder getSettingsOrBuilder();
}
