// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partner_api2.proto

package com.emporiaenergy.partnerapi2;

public interface DeviceUsageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:emporiaenergy.partner_api_2.DeviceUsageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .emporiaenergy.partner_api_2.DeviceUsageResponse.DeviceUsage device_usages = 1;</code>
   */
  java.util.List<com.emporiaenergy.partnerapi2.DeviceUsageResponse.DeviceUsage> 
      getDeviceUsagesList();
  /**
   * <code>repeated .emporiaenergy.partner_api_2.DeviceUsageResponse.DeviceUsage device_usages = 1;</code>
   */
  com.emporiaenergy.partnerapi2.DeviceUsageResponse.DeviceUsage getDeviceUsages(int index);
  /**
   * <code>repeated .emporiaenergy.partner_api_2.DeviceUsageResponse.DeviceUsage device_usages = 1;</code>
   */
  int getDeviceUsagesCount();
  /**
   * <code>repeated .emporiaenergy.partner_api_2.DeviceUsageResponse.DeviceUsage device_usages = 1;</code>
   */
  java.util.List<? extends com.emporiaenergy.partnerapi2.DeviceUsageResponse.DeviceUsageOrBuilder> 
      getDeviceUsagesOrBuilderList();
  /**
   * <code>repeated .emporiaenergy.partner_api_2.DeviceUsageResponse.DeviceUsage device_usages = 1;</code>
   */
  com.emporiaenergy.partnerapi2.DeviceUsageResponse.DeviceUsageOrBuilder getDeviceUsagesOrBuilder(
      int index);
}
