// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partner_api2.proto

package com.emporiaenergy.partnerapi2;

/**
 * Protobuf type {@code emporiaenergy.partner_api_2.EVChargersResponse}
 */
public final class EVChargersResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:emporiaenergy.partner_api_2.EVChargersResponse)
    EVChargersResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EVChargersResponse.newBuilder() to construct.
  private EVChargersResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EVChargersResponse() {
    evchargers_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EVChargersResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EVChargersResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              evchargers_ = new java.util.ArrayList<com.emporiaenergy.partnerapi2.EVCharger>();
              mutable_bitField0_ |= 0x00000001;
            }
            evchargers_.add(
                input.readMessage(com.emporiaenergy.partnerapi2.EVCharger.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        evchargers_ = java.util.Collections.unmodifiableList(evchargers_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.emporiaenergy.partnerapi2.PartnerApi2.internal_static_emporiaenergy_partner_api_2_EVChargersResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.emporiaenergy.partnerapi2.PartnerApi2.internal_static_emporiaenergy_partner_api_2_EVChargersResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.emporiaenergy.partnerapi2.EVChargersResponse.class, com.emporiaenergy.partnerapi2.EVChargersResponse.Builder.class);
  }

  public static final int EVCHARGERS_FIELD_NUMBER = 1;
  private java.util.List<com.emporiaenergy.partnerapi2.EVCharger> evchargers_;
  /**
   * <code>repeated .emporiaenergy.partner_api_2.EVCharger evchargers = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.emporiaenergy.partnerapi2.EVCharger> getEvchargersList() {
    return evchargers_;
  }
  /**
   * <code>repeated .emporiaenergy.partner_api_2.EVCharger evchargers = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.emporiaenergy.partnerapi2.EVChargerOrBuilder> 
      getEvchargersOrBuilderList() {
    return evchargers_;
  }
  /**
   * <code>repeated .emporiaenergy.partner_api_2.EVCharger evchargers = 1;</code>
   */
  @java.lang.Override
  public int getEvchargersCount() {
    return evchargers_.size();
  }
  /**
   * <code>repeated .emporiaenergy.partner_api_2.EVCharger evchargers = 1;</code>
   */
  @java.lang.Override
  public com.emporiaenergy.partnerapi2.EVCharger getEvchargers(int index) {
    return evchargers_.get(index);
  }
  /**
   * <code>repeated .emporiaenergy.partner_api_2.EVCharger evchargers = 1;</code>
   */
  @java.lang.Override
  public com.emporiaenergy.partnerapi2.EVChargerOrBuilder getEvchargersOrBuilder(
      int index) {
    return evchargers_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < evchargers_.size(); i++) {
      output.writeMessage(1, evchargers_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < evchargers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, evchargers_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.emporiaenergy.partnerapi2.EVChargersResponse)) {
      return super.equals(obj);
    }
    com.emporiaenergy.partnerapi2.EVChargersResponse other = (com.emporiaenergy.partnerapi2.EVChargersResponse) obj;

    if (!getEvchargersList()
        .equals(other.getEvchargersList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getEvchargersCount() > 0) {
      hash = (37 * hash) + EVCHARGERS_FIELD_NUMBER;
      hash = (53 * hash) + getEvchargersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.emporiaenergy.partnerapi2.EVChargersResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.emporiaenergy.partnerapi2.EVChargersResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.emporiaenergy.partnerapi2.EVChargersResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.emporiaenergy.partnerapi2.EVChargersResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.emporiaenergy.partnerapi2.EVChargersResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.emporiaenergy.partnerapi2.EVChargersResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.emporiaenergy.partnerapi2.EVChargersResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.emporiaenergy.partnerapi2.EVChargersResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.emporiaenergy.partnerapi2.EVChargersResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.emporiaenergy.partnerapi2.EVChargersResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.emporiaenergy.partnerapi2.EVChargersResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.emporiaenergy.partnerapi2.EVChargersResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.emporiaenergy.partnerapi2.EVChargersResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code emporiaenergy.partner_api_2.EVChargersResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:emporiaenergy.partner_api_2.EVChargersResponse)
      com.emporiaenergy.partnerapi2.EVChargersResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.emporiaenergy.partnerapi2.PartnerApi2.internal_static_emporiaenergy_partner_api_2_EVChargersResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.emporiaenergy.partnerapi2.PartnerApi2.internal_static_emporiaenergy_partner_api_2_EVChargersResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.emporiaenergy.partnerapi2.EVChargersResponse.class, com.emporiaenergy.partnerapi2.EVChargersResponse.Builder.class);
    }

    // Construct using com.emporiaenergy.partnerapi2.EVChargersResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getEvchargersFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (evchargersBuilder_ == null) {
        evchargers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        evchargersBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.emporiaenergy.partnerapi2.PartnerApi2.internal_static_emporiaenergy_partner_api_2_EVChargersResponse_descriptor;
    }

    @java.lang.Override
    public com.emporiaenergy.partnerapi2.EVChargersResponse getDefaultInstanceForType() {
      return com.emporiaenergy.partnerapi2.EVChargersResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.emporiaenergy.partnerapi2.EVChargersResponse build() {
      com.emporiaenergy.partnerapi2.EVChargersResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.emporiaenergy.partnerapi2.EVChargersResponse buildPartial() {
      com.emporiaenergy.partnerapi2.EVChargersResponse result = new com.emporiaenergy.partnerapi2.EVChargersResponse(this);
      int from_bitField0_ = bitField0_;
      if (evchargersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          evchargers_ = java.util.Collections.unmodifiableList(evchargers_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.evchargers_ = evchargers_;
      } else {
        result.evchargers_ = evchargersBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.emporiaenergy.partnerapi2.EVChargersResponse) {
        return mergeFrom((com.emporiaenergy.partnerapi2.EVChargersResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.emporiaenergy.partnerapi2.EVChargersResponse other) {
      if (other == com.emporiaenergy.partnerapi2.EVChargersResponse.getDefaultInstance()) return this;
      if (evchargersBuilder_ == null) {
        if (!other.evchargers_.isEmpty()) {
          if (evchargers_.isEmpty()) {
            evchargers_ = other.evchargers_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEvchargersIsMutable();
            evchargers_.addAll(other.evchargers_);
          }
          onChanged();
        }
      } else {
        if (!other.evchargers_.isEmpty()) {
          if (evchargersBuilder_.isEmpty()) {
            evchargersBuilder_.dispose();
            evchargersBuilder_ = null;
            evchargers_ = other.evchargers_;
            bitField0_ = (bitField0_ & ~0x00000001);
            evchargersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEvchargersFieldBuilder() : null;
          } else {
            evchargersBuilder_.addAllMessages(other.evchargers_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.emporiaenergy.partnerapi2.EVChargersResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.emporiaenergy.partnerapi2.EVChargersResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.emporiaenergy.partnerapi2.EVCharger> evchargers_ =
      java.util.Collections.emptyList();
    private void ensureEvchargersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        evchargers_ = new java.util.ArrayList<com.emporiaenergy.partnerapi2.EVCharger>(evchargers_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.emporiaenergy.partnerapi2.EVCharger, com.emporiaenergy.partnerapi2.EVCharger.Builder, com.emporiaenergy.partnerapi2.EVChargerOrBuilder> evchargersBuilder_;

    /**
     * <code>repeated .emporiaenergy.partner_api_2.EVCharger evchargers = 1;</code>
     */
    public java.util.List<com.emporiaenergy.partnerapi2.EVCharger> getEvchargersList() {
      if (evchargersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(evchargers_);
      } else {
        return evchargersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .emporiaenergy.partner_api_2.EVCharger evchargers = 1;</code>
     */
    public int getEvchargersCount() {
      if (evchargersBuilder_ == null) {
        return evchargers_.size();
      } else {
        return evchargersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .emporiaenergy.partner_api_2.EVCharger evchargers = 1;</code>
     */
    public com.emporiaenergy.partnerapi2.EVCharger getEvchargers(int index) {
      if (evchargersBuilder_ == null) {
        return evchargers_.get(index);
      } else {
        return evchargersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .emporiaenergy.partner_api_2.EVCharger evchargers = 1;</code>
     */
    public Builder setEvchargers(
        int index, com.emporiaenergy.partnerapi2.EVCharger value) {
      if (evchargersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEvchargersIsMutable();
        evchargers_.set(index, value);
        onChanged();
      } else {
        evchargersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .emporiaenergy.partner_api_2.EVCharger evchargers = 1;</code>
     */
    public Builder setEvchargers(
        int index, com.emporiaenergy.partnerapi2.EVCharger.Builder builderForValue) {
      if (evchargersBuilder_ == null) {
        ensureEvchargersIsMutable();
        evchargers_.set(index, builderForValue.build());
        onChanged();
      } else {
        evchargersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .emporiaenergy.partner_api_2.EVCharger evchargers = 1;</code>
     */
    public Builder addEvchargers(com.emporiaenergy.partnerapi2.EVCharger value) {
      if (evchargersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEvchargersIsMutable();
        evchargers_.add(value);
        onChanged();
      } else {
        evchargersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .emporiaenergy.partner_api_2.EVCharger evchargers = 1;</code>
     */
    public Builder addEvchargers(
        int index, com.emporiaenergy.partnerapi2.EVCharger value) {
      if (evchargersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEvchargersIsMutable();
        evchargers_.add(index, value);
        onChanged();
      } else {
        evchargersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .emporiaenergy.partner_api_2.EVCharger evchargers = 1;</code>
     */
    public Builder addEvchargers(
        com.emporiaenergy.partnerapi2.EVCharger.Builder builderForValue) {
      if (evchargersBuilder_ == null) {
        ensureEvchargersIsMutable();
        evchargers_.add(builderForValue.build());
        onChanged();
      } else {
        evchargersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .emporiaenergy.partner_api_2.EVCharger evchargers = 1;</code>
     */
    public Builder addEvchargers(
        int index, com.emporiaenergy.partnerapi2.EVCharger.Builder builderForValue) {
      if (evchargersBuilder_ == null) {
        ensureEvchargersIsMutable();
        evchargers_.add(index, builderForValue.build());
        onChanged();
      } else {
        evchargersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .emporiaenergy.partner_api_2.EVCharger evchargers = 1;</code>
     */
    public Builder addAllEvchargers(
        java.lang.Iterable<? extends com.emporiaenergy.partnerapi2.EVCharger> values) {
      if (evchargersBuilder_ == null) {
        ensureEvchargersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, evchargers_);
        onChanged();
      } else {
        evchargersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .emporiaenergy.partner_api_2.EVCharger evchargers = 1;</code>
     */
    public Builder clearEvchargers() {
      if (evchargersBuilder_ == null) {
        evchargers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        evchargersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .emporiaenergy.partner_api_2.EVCharger evchargers = 1;</code>
     */
    public Builder removeEvchargers(int index) {
      if (evchargersBuilder_ == null) {
        ensureEvchargersIsMutable();
        evchargers_.remove(index);
        onChanged();
      } else {
        evchargersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .emporiaenergy.partner_api_2.EVCharger evchargers = 1;</code>
     */
    public com.emporiaenergy.partnerapi2.EVCharger.Builder getEvchargersBuilder(
        int index) {
      return getEvchargersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .emporiaenergy.partner_api_2.EVCharger evchargers = 1;</code>
     */
    public com.emporiaenergy.partnerapi2.EVChargerOrBuilder getEvchargersOrBuilder(
        int index) {
      if (evchargersBuilder_ == null) {
        return evchargers_.get(index);  } else {
        return evchargersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .emporiaenergy.partner_api_2.EVCharger evchargers = 1;</code>
     */
    public java.util.List<? extends com.emporiaenergy.partnerapi2.EVChargerOrBuilder> 
         getEvchargersOrBuilderList() {
      if (evchargersBuilder_ != null) {
        return evchargersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(evchargers_);
      }
    }
    /**
     * <code>repeated .emporiaenergy.partner_api_2.EVCharger evchargers = 1;</code>
     */
    public com.emporiaenergy.partnerapi2.EVCharger.Builder addEvchargersBuilder() {
      return getEvchargersFieldBuilder().addBuilder(
          com.emporiaenergy.partnerapi2.EVCharger.getDefaultInstance());
    }
    /**
     * <code>repeated .emporiaenergy.partner_api_2.EVCharger evchargers = 1;</code>
     */
    public com.emporiaenergy.partnerapi2.EVCharger.Builder addEvchargersBuilder(
        int index) {
      return getEvchargersFieldBuilder().addBuilder(
          index, com.emporiaenergy.partnerapi2.EVCharger.getDefaultInstance());
    }
    /**
     * <code>repeated .emporiaenergy.partner_api_2.EVCharger evchargers = 1;</code>
     */
    public java.util.List<com.emporiaenergy.partnerapi2.EVCharger.Builder> 
         getEvchargersBuilderList() {
      return getEvchargersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.emporiaenergy.partnerapi2.EVCharger, com.emporiaenergy.partnerapi2.EVCharger.Builder, com.emporiaenergy.partnerapi2.EVChargerOrBuilder> 
        getEvchargersFieldBuilder() {
      if (evchargersBuilder_ == null) {
        evchargersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.emporiaenergy.partnerapi2.EVCharger, com.emporiaenergy.partnerapi2.EVCharger.Builder, com.emporiaenergy.partnerapi2.EVChargerOrBuilder>(
                evchargers_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        evchargers_ = null;
      }
      return evchargersBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:emporiaenergy.partner_api_2.EVChargersResponse)
  }

  // @@protoc_insertion_point(class_scope:emporiaenergy.partner_api_2.EVChargersResponse)
  private static final com.emporiaenergy.partnerapi2.EVChargersResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.emporiaenergy.partnerapi2.EVChargersResponse();
  }

  public static com.emporiaenergy.partnerapi2.EVChargersResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EVChargersResponse>
      PARSER = new com.google.protobuf.AbstractParser<EVChargersResponse>() {
    @java.lang.Override
    public EVChargersResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EVChargersResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EVChargersResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EVChargersResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.emporiaenergy.partnerapi2.EVChargersResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

