// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partner_api2.proto

package com.emporiaenergy.partnerapi2;

public interface EVChargerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:emporiaenergy.partner_api_2.EVCharger)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * is there a car connected to the EV Charger?  
   * </pre>
   *
   * <code>bool car_connected = 1;</code>
   * @return The carConnected.
   */
  boolean getCarConnected();

  /**
   * <pre>
   * is the car actively taking power from the charger?  If the car is connected but full or the charger is not set to On then this will be false 
   * </pre>
   *
   * <code>bool car_charging = 2;</code>
   * @return The carCharging.
   */
  boolean getCarCharging();

  /**
   * <pre>
   * maximum rate that the charger may be set at; configured by the customer based on their breaker size
   * </pre>
   *
   * <code>uint32 max_charge_rate_amps = 3;</code>
   * @return The maxChargeRateAmps.
   */
  int getMaxChargeRateAmps();

  /**
   * <pre>
   * the settings that may be changed using the API, starting at a higher index to leave room for additional non-changeable fields
   * </pre>
   *
   * <code>.emporiaenergy.partner_api_2.EVChargerSettings settings = 10;</code>
   * @return Whether the settings field is set.
   */
  boolean hasSettings();
  /**
   * <pre>
   * the settings that may be changed using the API, starting at a higher index to leave room for additional non-changeable fields
   * </pre>
   *
   * <code>.emporiaenergy.partner_api_2.EVChargerSettings settings = 10;</code>
   * @return The settings.
   */
  com.emporiaenergy.partnerapi2.EVChargerSettings getSettings();
  /**
   * <pre>
   * the settings that may be changed using the API, starting at a higher index to leave room for additional non-changeable fields
   * </pre>
   *
   * <code>.emporiaenergy.partner_api_2.EVChargerSettings settings = 10;</code>
   */
  com.emporiaenergy.partnerapi2.EVChargerSettingsOrBuilder getSettingsOrBuilder();
}
