// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partner_api2.proto

package com.emporiaenergy.partnerapi2;

public interface EVChargersResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:emporiaenergy.partner_api_2.EVChargersResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .emporiaenergy.partner_api_2.EVCharger evchargers = 1;</code>
   */
  java.util.List<com.emporiaenergy.partnerapi2.EVCharger> 
      getEvchargersList();
  /**
   * <code>repeated .emporiaenergy.partner_api_2.EVCharger evchargers = 1;</code>
   */
  com.emporiaenergy.partnerapi2.EVCharger getEvchargers(int index);
  /**
   * <code>repeated .emporiaenergy.partner_api_2.EVCharger evchargers = 1;</code>
   */
  int getEvchargersCount();
  /**
   * <code>repeated .emporiaenergy.partner_api_2.EVCharger evchargers = 1;</code>
   */
  java.util.List<? extends com.emporiaenergy.partnerapi2.EVChargerOrBuilder> 
      getEvchargersOrBuilderList();
  /**
   * <code>repeated .emporiaenergy.partner_api_2.EVCharger evchargers = 1;</code>
   */
  com.emporiaenergy.partnerapi2.EVChargerOrBuilder getEvchargersOrBuilder(
      int index);
}
