// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partner_api2.proto

package com.emporiaenergy.partnerapi2;

/**
 * <pre>
 **
 * The EVChargers's settings, this structure is both returned to partners and sent back to Emporia to control the battery.  
 * When returned from Emporia to a client all the fields will be set; i.e., both the on and charge_rate_amps will be set.
 * When sent to Emporia to change the battery settings it is not required to set all the fields in settings.
 * I.e., you can change charge_rate_amps without setting the on field.
 * </pre>
 *
 * Protobuf type {@code emporiaenergy.partner_api_2.EVChargerSettings}
 */
public final class EVChargerSettings extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:emporiaenergy.partner_api_2.EVChargerSettings)
    EVChargerSettingsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EVChargerSettings.newBuilder() to construct.
  private EVChargerSettings(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EVChargerSettings() {
    manufacturerDeviceId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EVChargerSettings();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EVChargerSettings(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            manufacturerDeviceId_ = s;
            break;
          }
          case 18: {
            com.google.protobuf.BoolValue.Builder subBuilder = null;
            if (on_ != null) {
              subBuilder = on_.toBuilder();
            }
            on_ = input.readMessage(com.google.protobuf.BoolValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(on_);
              on_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.google.protobuf.UInt32Value.Builder subBuilder = null;
            if (chargeRateAmps_ != null) {
              subBuilder = chargeRateAmps_.toBuilder();
            }
            chargeRateAmps_ = input.readMessage(com.google.protobuf.UInt32Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(chargeRateAmps_);
              chargeRateAmps_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.emporiaenergy.partnerapi2.PartnerApi2.internal_static_emporiaenergy_partner_api_2_EVChargerSettings_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.emporiaenergy.partnerapi2.PartnerApi2.internal_static_emporiaenergy_partner_api_2_EVChargerSettings_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.emporiaenergy.partnerapi2.EVChargerSettings.class, com.emporiaenergy.partnerapi2.EVChargerSettings.Builder.class);
  }

  public static final int MANUFACTURER_DEVICE_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object manufacturerDeviceId_;
  /**
   * <pre>
   * identifies this device 
   * </pre>
   *
   * <code>string manufacturer_device_id = 1;</code>
   * @return The manufacturerDeviceId.
   */
  @java.lang.Override
  public java.lang.String getManufacturerDeviceId() {
    java.lang.Object ref = manufacturerDeviceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      manufacturerDeviceId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * identifies this device 
   * </pre>
   *
   * <code>string manufacturer_device_id = 1;</code>
   * @return The bytes for manufacturerDeviceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getManufacturerDeviceIdBytes() {
    java.lang.Object ref = manufacturerDeviceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      manufacturerDeviceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ON_FIELD_NUMBER = 2;
  private com.google.protobuf.BoolValue on_;
  /**
   * <pre>
   * Is the charger set to charge?
   * </pre>
   *
   * <code>.google.protobuf.BoolValue on = 2;</code>
   * @return Whether the on field is set.
   */
  @java.lang.Override
  public boolean hasOn() {
    return on_ != null;
  }
  /**
   * <pre>
   * Is the charger set to charge?
   * </pre>
   *
   * <code>.google.protobuf.BoolValue on = 2;</code>
   * @return The on.
   */
  @java.lang.Override
  public com.google.protobuf.BoolValue getOn() {
    return on_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : on_;
  }
  /**
   * <pre>
   * Is the charger set to charge?
   * </pre>
   *
   * <code>.google.protobuf.BoolValue on = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.BoolValueOrBuilder getOnOrBuilder() {
    return getOn();
  }

  public static final int CHARGE_RATE_AMPS_FIELD_NUMBER = 3;
  private com.google.protobuf.UInt32Value chargeRateAmps_;
  /**
   * <pre>
   * must be between 6 and the max_charge_rate_amps (inclusive)
   * </pre>
   *
   * <code>.google.protobuf.UInt32Value charge_rate_amps = 3;</code>
   * @return Whether the chargeRateAmps field is set.
   */
  @java.lang.Override
  public boolean hasChargeRateAmps() {
    return chargeRateAmps_ != null;
  }
  /**
   * <pre>
   * must be between 6 and the max_charge_rate_amps (inclusive)
   * </pre>
   *
   * <code>.google.protobuf.UInt32Value charge_rate_amps = 3;</code>
   * @return The chargeRateAmps.
   */
  @java.lang.Override
  public com.google.protobuf.UInt32Value getChargeRateAmps() {
    return chargeRateAmps_ == null ? com.google.protobuf.UInt32Value.getDefaultInstance() : chargeRateAmps_;
  }
  /**
   * <pre>
   * must be between 6 and the max_charge_rate_amps (inclusive)
   * </pre>
   *
   * <code>.google.protobuf.UInt32Value charge_rate_amps = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.UInt32ValueOrBuilder getChargeRateAmpsOrBuilder() {
    return getChargeRateAmps();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getManufacturerDeviceIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, manufacturerDeviceId_);
    }
    if (on_ != null) {
      output.writeMessage(2, getOn());
    }
    if (chargeRateAmps_ != null) {
      output.writeMessage(3, getChargeRateAmps());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getManufacturerDeviceIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, manufacturerDeviceId_);
    }
    if (on_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getOn());
    }
    if (chargeRateAmps_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getChargeRateAmps());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.emporiaenergy.partnerapi2.EVChargerSettings)) {
      return super.equals(obj);
    }
    com.emporiaenergy.partnerapi2.EVChargerSettings other = (com.emporiaenergy.partnerapi2.EVChargerSettings) obj;

    if (!getManufacturerDeviceId()
        .equals(other.getManufacturerDeviceId())) return false;
    if (hasOn() != other.hasOn()) return false;
    if (hasOn()) {
      if (!getOn()
          .equals(other.getOn())) return false;
    }
    if (hasChargeRateAmps() != other.hasChargeRateAmps()) return false;
    if (hasChargeRateAmps()) {
      if (!getChargeRateAmps()
          .equals(other.getChargeRateAmps())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MANUFACTURER_DEVICE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getManufacturerDeviceId().hashCode();
    if (hasOn()) {
      hash = (37 * hash) + ON_FIELD_NUMBER;
      hash = (53 * hash) + getOn().hashCode();
    }
    if (hasChargeRateAmps()) {
      hash = (37 * hash) + CHARGE_RATE_AMPS_FIELD_NUMBER;
      hash = (53 * hash) + getChargeRateAmps().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.emporiaenergy.partnerapi2.EVChargerSettings parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.emporiaenergy.partnerapi2.EVChargerSettings parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.emporiaenergy.partnerapi2.EVChargerSettings parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.emporiaenergy.partnerapi2.EVChargerSettings parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.emporiaenergy.partnerapi2.EVChargerSettings parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.emporiaenergy.partnerapi2.EVChargerSettings parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.emporiaenergy.partnerapi2.EVChargerSettings parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.emporiaenergy.partnerapi2.EVChargerSettings parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.emporiaenergy.partnerapi2.EVChargerSettings parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.emporiaenergy.partnerapi2.EVChargerSettings parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.emporiaenergy.partnerapi2.EVChargerSettings parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.emporiaenergy.partnerapi2.EVChargerSettings parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.emporiaenergy.partnerapi2.EVChargerSettings prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * The EVChargers's settings, this structure is both returned to partners and sent back to Emporia to control the battery.  
   * When returned from Emporia to a client all the fields will be set; i.e., both the on and charge_rate_amps will be set.
   * When sent to Emporia to change the battery settings it is not required to set all the fields in settings.
   * I.e., you can change charge_rate_amps without setting the on field.
   * </pre>
   *
   * Protobuf type {@code emporiaenergy.partner_api_2.EVChargerSettings}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:emporiaenergy.partner_api_2.EVChargerSettings)
      com.emporiaenergy.partnerapi2.EVChargerSettingsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.emporiaenergy.partnerapi2.PartnerApi2.internal_static_emporiaenergy_partner_api_2_EVChargerSettings_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.emporiaenergy.partnerapi2.PartnerApi2.internal_static_emporiaenergy_partner_api_2_EVChargerSettings_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.emporiaenergy.partnerapi2.EVChargerSettings.class, com.emporiaenergy.partnerapi2.EVChargerSettings.Builder.class);
    }

    // Construct using com.emporiaenergy.partnerapi2.EVChargerSettings.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      manufacturerDeviceId_ = "";

      if (onBuilder_ == null) {
        on_ = null;
      } else {
        on_ = null;
        onBuilder_ = null;
      }
      if (chargeRateAmpsBuilder_ == null) {
        chargeRateAmps_ = null;
      } else {
        chargeRateAmps_ = null;
        chargeRateAmpsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.emporiaenergy.partnerapi2.PartnerApi2.internal_static_emporiaenergy_partner_api_2_EVChargerSettings_descriptor;
    }

    @java.lang.Override
    public com.emporiaenergy.partnerapi2.EVChargerSettings getDefaultInstanceForType() {
      return com.emporiaenergy.partnerapi2.EVChargerSettings.getDefaultInstance();
    }

    @java.lang.Override
    public com.emporiaenergy.partnerapi2.EVChargerSettings build() {
      com.emporiaenergy.partnerapi2.EVChargerSettings result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.emporiaenergy.partnerapi2.EVChargerSettings buildPartial() {
      com.emporiaenergy.partnerapi2.EVChargerSettings result = new com.emporiaenergy.partnerapi2.EVChargerSettings(this);
      result.manufacturerDeviceId_ = manufacturerDeviceId_;
      if (onBuilder_ == null) {
        result.on_ = on_;
      } else {
        result.on_ = onBuilder_.build();
      }
      if (chargeRateAmpsBuilder_ == null) {
        result.chargeRateAmps_ = chargeRateAmps_;
      } else {
        result.chargeRateAmps_ = chargeRateAmpsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.emporiaenergy.partnerapi2.EVChargerSettings) {
        return mergeFrom((com.emporiaenergy.partnerapi2.EVChargerSettings)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.emporiaenergy.partnerapi2.EVChargerSettings other) {
      if (other == com.emporiaenergy.partnerapi2.EVChargerSettings.getDefaultInstance()) return this;
      if (!other.getManufacturerDeviceId().isEmpty()) {
        manufacturerDeviceId_ = other.manufacturerDeviceId_;
        onChanged();
      }
      if (other.hasOn()) {
        mergeOn(other.getOn());
      }
      if (other.hasChargeRateAmps()) {
        mergeChargeRateAmps(other.getChargeRateAmps());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.emporiaenergy.partnerapi2.EVChargerSettings parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.emporiaenergy.partnerapi2.EVChargerSettings) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object manufacturerDeviceId_ = "";
    /**
     * <pre>
     * identifies this device 
     * </pre>
     *
     * <code>string manufacturer_device_id = 1;</code>
     * @return The manufacturerDeviceId.
     */
    public java.lang.String getManufacturerDeviceId() {
      java.lang.Object ref = manufacturerDeviceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        manufacturerDeviceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * identifies this device 
     * </pre>
     *
     * <code>string manufacturer_device_id = 1;</code>
     * @return The bytes for manufacturerDeviceId.
     */
    public com.google.protobuf.ByteString
        getManufacturerDeviceIdBytes() {
      java.lang.Object ref = manufacturerDeviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        manufacturerDeviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * identifies this device 
     * </pre>
     *
     * <code>string manufacturer_device_id = 1;</code>
     * @param value The manufacturerDeviceId to set.
     * @return This builder for chaining.
     */
    public Builder setManufacturerDeviceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      manufacturerDeviceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * identifies this device 
     * </pre>
     *
     * <code>string manufacturer_device_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearManufacturerDeviceId() {
      
      manufacturerDeviceId_ = getDefaultInstance().getManufacturerDeviceId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * identifies this device 
     * </pre>
     *
     * <code>string manufacturer_device_id = 1;</code>
     * @param value The bytes for manufacturerDeviceId to set.
     * @return This builder for chaining.
     */
    public Builder setManufacturerDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      manufacturerDeviceId_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.BoolValue on_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> onBuilder_;
    /**
     * <pre>
     * Is the charger set to charge?
     * </pre>
     *
     * <code>.google.protobuf.BoolValue on = 2;</code>
     * @return Whether the on field is set.
     */
    public boolean hasOn() {
      return onBuilder_ != null || on_ != null;
    }
    /**
     * <pre>
     * Is the charger set to charge?
     * </pre>
     *
     * <code>.google.protobuf.BoolValue on = 2;</code>
     * @return The on.
     */
    public com.google.protobuf.BoolValue getOn() {
      if (onBuilder_ == null) {
        return on_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : on_;
      } else {
        return onBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Is the charger set to charge?
     * </pre>
     *
     * <code>.google.protobuf.BoolValue on = 2;</code>
     */
    public Builder setOn(com.google.protobuf.BoolValue value) {
      if (onBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        on_ = value;
        onChanged();
      } else {
        onBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Is the charger set to charge?
     * </pre>
     *
     * <code>.google.protobuf.BoolValue on = 2;</code>
     */
    public Builder setOn(
        com.google.protobuf.BoolValue.Builder builderForValue) {
      if (onBuilder_ == null) {
        on_ = builderForValue.build();
        onChanged();
      } else {
        onBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Is the charger set to charge?
     * </pre>
     *
     * <code>.google.protobuf.BoolValue on = 2;</code>
     */
    public Builder mergeOn(com.google.protobuf.BoolValue value) {
      if (onBuilder_ == null) {
        if (on_ != null) {
          on_ =
            com.google.protobuf.BoolValue.newBuilder(on_).mergeFrom(value).buildPartial();
        } else {
          on_ = value;
        }
        onChanged();
      } else {
        onBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Is the charger set to charge?
     * </pre>
     *
     * <code>.google.protobuf.BoolValue on = 2;</code>
     */
    public Builder clearOn() {
      if (onBuilder_ == null) {
        on_ = null;
        onChanged();
      } else {
        on_ = null;
        onBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Is the charger set to charge?
     * </pre>
     *
     * <code>.google.protobuf.BoolValue on = 2;</code>
     */
    public com.google.protobuf.BoolValue.Builder getOnBuilder() {
      
      onChanged();
      return getOnFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Is the charger set to charge?
     * </pre>
     *
     * <code>.google.protobuf.BoolValue on = 2;</code>
     */
    public com.google.protobuf.BoolValueOrBuilder getOnOrBuilder() {
      if (onBuilder_ != null) {
        return onBuilder_.getMessageOrBuilder();
      } else {
        return on_ == null ?
            com.google.protobuf.BoolValue.getDefaultInstance() : on_;
      }
    }
    /**
     * <pre>
     * Is the charger set to charge?
     * </pre>
     *
     * <code>.google.protobuf.BoolValue on = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> 
        getOnFieldBuilder() {
      if (onBuilder_ == null) {
        onBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder>(
                getOn(),
                getParentForChildren(),
                isClean());
        on_ = null;
      }
      return onBuilder_;
    }

    private com.google.protobuf.UInt32Value chargeRateAmps_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.UInt32Value, com.google.protobuf.UInt32Value.Builder, com.google.protobuf.UInt32ValueOrBuilder> chargeRateAmpsBuilder_;
    /**
     * <pre>
     * must be between 6 and the max_charge_rate_amps (inclusive)
     * </pre>
     *
     * <code>.google.protobuf.UInt32Value charge_rate_amps = 3;</code>
     * @return Whether the chargeRateAmps field is set.
     */
    public boolean hasChargeRateAmps() {
      return chargeRateAmpsBuilder_ != null || chargeRateAmps_ != null;
    }
    /**
     * <pre>
     * must be between 6 and the max_charge_rate_amps (inclusive)
     * </pre>
     *
     * <code>.google.protobuf.UInt32Value charge_rate_amps = 3;</code>
     * @return The chargeRateAmps.
     */
    public com.google.protobuf.UInt32Value getChargeRateAmps() {
      if (chargeRateAmpsBuilder_ == null) {
        return chargeRateAmps_ == null ? com.google.protobuf.UInt32Value.getDefaultInstance() : chargeRateAmps_;
      } else {
        return chargeRateAmpsBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * must be between 6 and the max_charge_rate_amps (inclusive)
     * </pre>
     *
     * <code>.google.protobuf.UInt32Value charge_rate_amps = 3;</code>
     */
    public Builder setChargeRateAmps(com.google.protobuf.UInt32Value value) {
      if (chargeRateAmpsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        chargeRateAmps_ = value;
        onChanged();
      } else {
        chargeRateAmpsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * must be between 6 and the max_charge_rate_amps (inclusive)
     * </pre>
     *
     * <code>.google.protobuf.UInt32Value charge_rate_amps = 3;</code>
     */
    public Builder setChargeRateAmps(
        com.google.protobuf.UInt32Value.Builder builderForValue) {
      if (chargeRateAmpsBuilder_ == null) {
        chargeRateAmps_ = builderForValue.build();
        onChanged();
      } else {
        chargeRateAmpsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * must be between 6 and the max_charge_rate_amps (inclusive)
     * </pre>
     *
     * <code>.google.protobuf.UInt32Value charge_rate_amps = 3;</code>
     */
    public Builder mergeChargeRateAmps(com.google.protobuf.UInt32Value value) {
      if (chargeRateAmpsBuilder_ == null) {
        if (chargeRateAmps_ != null) {
          chargeRateAmps_ =
            com.google.protobuf.UInt32Value.newBuilder(chargeRateAmps_).mergeFrom(value).buildPartial();
        } else {
          chargeRateAmps_ = value;
        }
        onChanged();
      } else {
        chargeRateAmpsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * must be between 6 and the max_charge_rate_amps (inclusive)
     * </pre>
     *
     * <code>.google.protobuf.UInt32Value charge_rate_amps = 3;</code>
     */
    public Builder clearChargeRateAmps() {
      if (chargeRateAmpsBuilder_ == null) {
        chargeRateAmps_ = null;
        onChanged();
      } else {
        chargeRateAmps_ = null;
        chargeRateAmpsBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * must be between 6 and the max_charge_rate_amps (inclusive)
     * </pre>
     *
     * <code>.google.protobuf.UInt32Value charge_rate_amps = 3;</code>
     */
    public com.google.protobuf.UInt32Value.Builder getChargeRateAmpsBuilder() {
      
      onChanged();
      return getChargeRateAmpsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * must be between 6 and the max_charge_rate_amps (inclusive)
     * </pre>
     *
     * <code>.google.protobuf.UInt32Value charge_rate_amps = 3;</code>
     */
    public com.google.protobuf.UInt32ValueOrBuilder getChargeRateAmpsOrBuilder() {
      if (chargeRateAmpsBuilder_ != null) {
        return chargeRateAmpsBuilder_.getMessageOrBuilder();
      } else {
        return chargeRateAmps_ == null ?
            com.google.protobuf.UInt32Value.getDefaultInstance() : chargeRateAmps_;
      }
    }
    /**
     * <pre>
     * must be between 6 and the max_charge_rate_amps (inclusive)
     * </pre>
     *
     * <code>.google.protobuf.UInt32Value charge_rate_amps = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.UInt32Value, com.google.protobuf.UInt32Value.Builder, com.google.protobuf.UInt32ValueOrBuilder> 
        getChargeRateAmpsFieldBuilder() {
      if (chargeRateAmpsBuilder_ == null) {
        chargeRateAmpsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.UInt32Value, com.google.protobuf.UInt32Value.Builder, com.google.protobuf.UInt32ValueOrBuilder>(
                getChargeRateAmps(),
                getParentForChildren(),
                isClean());
        chargeRateAmps_ = null;
      }
      return chargeRateAmpsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:emporiaenergy.partner_api_2.EVChargerSettings)
  }

  // @@protoc_insertion_point(class_scope:emporiaenergy.partner_api_2.EVChargerSettings)
  private static final com.emporiaenergy.partnerapi2.EVChargerSettings DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.emporiaenergy.partnerapi2.EVChargerSettings();
  }

  public static com.emporiaenergy.partnerapi2.EVChargerSettings getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EVChargerSettings>
      PARSER = new com.google.protobuf.AbstractParser<EVChargerSettings>() {
    @java.lang.Override
    public EVChargerSettings parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EVChargerSettings(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EVChargerSettings> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EVChargerSettings> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.emporiaenergy.partnerapi2.EVChargerSettings getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

