// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partner_api2.proto

package com.emporiaenergy.partnerapi2;

public interface ListDevicesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:emporiaenergy.partner_api_2.ListDevicesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string auth_token = 1;</code>
   * @return The authToken.
   */
  java.lang.String getAuthToken();
  /**
   * <code>string auth_token = 1;</code>
   * @return The bytes for authToken.
   */
  com.google.protobuf.ByteString
      getAuthTokenBytes();

  /**
   * <pre>
   * If empty, return all devices associated with partner. This is limited by the Model; e.g., calling ListOutlets will only return outlets
   * if not empty, limit the returned devices to the specified MDIs
   * </pre>
   *
   * <code>repeated string manufacturer_device_ids = 2;</code>
   * @return A list containing the manufacturerDeviceIds.
   */
  java.util.List<java.lang.String>
      getManufacturerDeviceIdsList();
  /**
   * <pre>
   * If empty, return all devices associated with partner. This is limited by the Model; e.g., calling ListOutlets will only return outlets
   * if not empty, limit the returned devices to the specified MDIs
   * </pre>
   *
   * <code>repeated string manufacturer_device_ids = 2;</code>
   * @return The count of manufacturerDeviceIds.
   */
  int getManufacturerDeviceIdsCount();
  /**
   * <pre>
   * If empty, return all devices associated with partner. This is limited by the Model; e.g., calling ListOutlets will only return outlets
   * if not empty, limit the returned devices to the specified MDIs
   * </pre>
   *
   * <code>repeated string manufacturer_device_ids = 2;</code>
   * @param index The index of the element to return.
   * @return The manufacturerDeviceIds at the given index.
   */
  java.lang.String getManufacturerDeviceIds(int index);
  /**
   * <pre>
   * If empty, return all devices associated with partner. This is limited by the Model; e.g., calling ListOutlets will only return outlets
   * if not empty, limit the returned devices to the specified MDIs
   * </pre>
   *
   * <code>repeated string manufacturer_device_ids = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the manufacturerDeviceIds at the given index.
   */
  com.google.protobuf.ByteString
      getManufacturerDeviceIdsBytes(int index);
}
