// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partner_api2.proto

package com.emporiaenergy.partnerapi2;

public interface OutletsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:emporiaenergy.partner_api_2.OutletsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .emporiaenergy.partner_api_2.OutletSettings outlets = 1;</code>
   */
  java.util.List<com.emporiaenergy.partnerapi2.OutletSettings> 
      getOutletsList();
  /**
   * <code>repeated .emporiaenergy.partner_api_2.OutletSettings outlets = 1;</code>
   */
  com.emporiaenergy.partnerapi2.OutletSettings getOutlets(int index);
  /**
   * <code>repeated .emporiaenergy.partner_api_2.OutletSettings outlets = 1;</code>
   */
  int getOutletsCount();
  /**
   * <code>repeated .emporiaenergy.partner_api_2.OutletSettings outlets = 1;</code>
   */
  java.util.List<? extends com.emporiaenergy.partnerapi2.OutletSettingsOrBuilder> 
      getOutletsOrBuilderList();
  /**
   * <code>repeated .emporiaenergy.partner_api_2.OutletSettings outlets = 1;</code>
   */
  com.emporiaenergy.partnerapi2.OutletSettingsOrBuilder getOutletsOrBuilder(
      int index);
}
