// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partner_api2.proto

package com.emporiaenergy.partnerapi2;

public interface OutletSettingsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:emporiaenergy.partner_api_2.OutletSettings)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string manufacturer_device_id = 1;</code>
   * @return The manufacturerDeviceId.
   */
  java.lang.String getManufacturerDeviceId();
  /**
   * <code>string manufacturer_device_id = 1;</code>
   * @return The bytes for manufacturerDeviceId.
   */
  com.google.protobuf.ByteString
      getManufacturerDeviceIdBytes();

  /**
   * <pre>
   * If device_connected for an Outlet is false, the On/Off status may be out of date
   * </pre>
   *
   * <code>bool on = 2;</code>
   * @return The on.
   */
  boolean getOn();
}
