// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partner_api2.proto

package com.emporiaenergy.partnerapi2;

/**
 * <pre>
 * Represents a single Emporia Outlet.  This is used both in the response from 
 * the API describing the current state and in the UpdateOutlets method to turn an Outlet on or off.
 * </pre>
 *
 * Protobuf type {@code emporiaenergy.partner_api_2.OutletSettings}
 */
public final class OutletSettings extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:emporiaenergy.partner_api_2.OutletSettings)
    OutletSettingsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OutletSettings.newBuilder() to construct.
  private OutletSettings(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OutletSettings() {
    manufacturerDeviceId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OutletSettings();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OutletSettings(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            manufacturerDeviceId_ = s;
            break;
          }
          case 16: {

            on_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.emporiaenergy.partnerapi2.PartnerApi2.internal_static_emporiaenergy_partner_api_2_OutletSettings_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.emporiaenergy.partnerapi2.PartnerApi2.internal_static_emporiaenergy_partner_api_2_OutletSettings_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.emporiaenergy.partnerapi2.OutletSettings.class, com.emporiaenergy.partnerapi2.OutletSettings.Builder.class);
  }

  public static final int MANUFACTURER_DEVICE_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object manufacturerDeviceId_;
  /**
   * <code>string manufacturer_device_id = 1;</code>
   * @return The manufacturerDeviceId.
   */
  @java.lang.Override
  public java.lang.String getManufacturerDeviceId() {
    java.lang.Object ref = manufacturerDeviceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      manufacturerDeviceId_ = s;
      return s;
    }
  }
  /**
   * <code>string manufacturer_device_id = 1;</code>
   * @return The bytes for manufacturerDeviceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getManufacturerDeviceIdBytes() {
    java.lang.Object ref = manufacturerDeviceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      manufacturerDeviceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ON_FIELD_NUMBER = 2;
  private boolean on_;
  /**
   * <pre>
   * If device_connected for an Outlet is false, the On/Off status may be out of date
   * </pre>
   *
   * <code>bool on = 2;</code>
   * @return The on.
   */
  @java.lang.Override
  public boolean getOn() {
    return on_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getManufacturerDeviceIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, manufacturerDeviceId_);
    }
    if (on_ != false) {
      output.writeBool(2, on_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getManufacturerDeviceIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, manufacturerDeviceId_);
    }
    if (on_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, on_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.emporiaenergy.partnerapi2.OutletSettings)) {
      return super.equals(obj);
    }
    com.emporiaenergy.partnerapi2.OutletSettings other = (com.emporiaenergy.partnerapi2.OutletSettings) obj;

    if (!getManufacturerDeviceId()
        .equals(other.getManufacturerDeviceId())) return false;
    if (getOn()
        != other.getOn()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MANUFACTURER_DEVICE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getManufacturerDeviceId().hashCode();
    hash = (37 * hash) + ON_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getOn());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.emporiaenergy.partnerapi2.OutletSettings parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.emporiaenergy.partnerapi2.OutletSettings parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.emporiaenergy.partnerapi2.OutletSettings parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.emporiaenergy.partnerapi2.OutletSettings parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.emporiaenergy.partnerapi2.OutletSettings parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.emporiaenergy.partnerapi2.OutletSettings parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.emporiaenergy.partnerapi2.OutletSettings parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.emporiaenergy.partnerapi2.OutletSettings parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.emporiaenergy.partnerapi2.OutletSettings parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.emporiaenergy.partnerapi2.OutletSettings parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.emporiaenergy.partnerapi2.OutletSettings parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.emporiaenergy.partnerapi2.OutletSettings parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.emporiaenergy.partnerapi2.OutletSettings prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Represents a single Emporia Outlet.  This is used both in the response from 
   * the API describing the current state and in the UpdateOutlets method to turn an Outlet on or off.
   * </pre>
   *
   * Protobuf type {@code emporiaenergy.partner_api_2.OutletSettings}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:emporiaenergy.partner_api_2.OutletSettings)
      com.emporiaenergy.partnerapi2.OutletSettingsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.emporiaenergy.partnerapi2.PartnerApi2.internal_static_emporiaenergy_partner_api_2_OutletSettings_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.emporiaenergy.partnerapi2.PartnerApi2.internal_static_emporiaenergy_partner_api_2_OutletSettings_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.emporiaenergy.partnerapi2.OutletSettings.class, com.emporiaenergy.partnerapi2.OutletSettings.Builder.class);
    }

    // Construct using com.emporiaenergy.partnerapi2.OutletSettings.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      manufacturerDeviceId_ = "";

      on_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.emporiaenergy.partnerapi2.PartnerApi2.internal_static_emporiaenergy_partner_api_2_OutletSettings_descriptor;
    }

    @java.lang.Override
    public com.emporiaenergy.partnerapi2.OutletSettings getDefaultInstanceForType() {
      return com.emporiaenergy.partnerapi2.OutletSettings.getDefaultInstance();
    }

    @java.lang.Override
    public com.emporiaenergy.partnerapi2.OutletSettings build() {
      com.emporiaenergy.partnerapi2.OutletSettings result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.emporiaenergy.partnerapi2.OutletSettings buildPartial() {
      com.emporiaenergy.partnerapi2.OutletSettings result = new com.emporiaenergy.partnerapi2.OutletSettings(this);
      result.manufacturerDeviceId_ = manufacturerDeviceId_;
      result.on_ = on_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.emporiaenergy.partnerapi2.OutletSettings) {
        return mergeFrom((com.emporiaenergy.partnerapi2.OutletSettings)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.emporiaenergy.partnerapi2.OutletSettings other) {
      if (other == com.emporiaenergy.partnerapi2.OutletSettings.getDefaultInstance()) return this;
      if (!other.getManufacturerDeviceId().isEmpty()) {
        manufacturerDeviceId_ = other.manufacturerDeviceId_;
        onChanged();
      }
      if (other.getOn() != false) {
        setOn(other.getOn());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.emporiaenergy.partnerapi2.OutletSettings parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.emporiaenergy.partnerapi2.OutletSettings) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object manufacturerDeviceId_ = "";
    /**
     * <code>string manufacturer_device_id = 1;</code>
     * @return The manufacturerDeviceId.
     */
    public java.lang.String getManufacturerDeviceId() {
      java.lang.Object ref = manufacturerDeviceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        manufacturerDeviceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string manufacturer_device_id = 1;</code>
     * @return The bytes for manufacturerDeviceId.
     */
    public com.google.protobuf.ByteString
        getManufacturerDeviceIdBytes() {
      java.lang.Object ref = manufacturerDeviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        manufacturerDeviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string manufacturer_device_id = 1;</code>
     * @param value The manufacturerDeviceId to set.
     * @return This builder for chaining.
     */
    public Builder setManufacturerDeviceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      manufacturerDeviceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string manufacturer_device_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearManufacturerDeviceId() {
      
      manufacturerDeviceId_ = getDefaultInstance().getManufacturerDeviceId();
      onChanged();
      return this;
    }
    /**
     * <code>string manufacturer_device_id = 1;</code>
     * @param value The bytes for manufacturerDeviceId to set.
     * @return This builder for chaining.
     */
    public Builder setManufacturerDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      manufacturerDeviceId_ = value;
      onChanged();
      return this;
    }

    private boolean on_ ;
    /**
     * <pre>
     * If device_connected for an Outlet is false, the On/Off status may be out of date
     * </pre>
     *
     * <code>bool on = 2;</code>
     * @return The on.
     */
    @java.lang.Override
    public boolean getOn() {
      return on_;
    }
    /**
     * <pre>
     * If device_connected for an Outlet is false, the On/Off status may be out of date
     * </pre>
     *
     * <code>bool on = 2;</code>
     * @param value The on to set.
     * @return This builder for chaining.
     */
    public Builder setOn(boolean value) {
      
      on_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If device_connected for an Outlet is false, the On/Off status may be out of date
     * </pre>
     *
     * <code>bool on = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearOn() {
      
      on_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:emporiaenergy.partner_api_2.OutletSettings)
  }

  // @@protoc_insertion_point(class_scope:emporiaenergy.partner_api_2.OutletSettings)
  private static final com.emporiaenergy.partnerapi2.OutletSettings DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.emporiaenergy.partnerapi2.OutletSettings();
  }

  public static com.emporiaenergy.partnerapi2.OutletSettings getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OutletSettings>
      PARSER = new com.google.protobuf.AbstractParser<OutletSettings>() {
    @java.lang.Override
    public OutletSettings parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OutletSettings(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OutletSettings> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OutletSettings> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.emporiaenergy.partnerapi2.OutletSettings getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

