// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partner_api2.proto

package com.emporiaenergy.partnerapi2;

public final class PartnerApi2 {
  private PartnerApi2() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emporiaenergy_partner_api_2_AuthenticationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emporiaenergy_partner_api_2_AuthenticationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emporiaenergy_partner_api_2_AuthenticationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emporiaenergy_partner_api_2_AuthenticationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emporiaenergy_partner_api_2_DeviceInventoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emporiaenergy_partner_api_2_DeviceInventoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emporiaenergy_partner_api_2_DeviceInventoryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emporiaenergy_partner_api_2_DeviceInventoryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emporiaenergy_partner_api_2_DeviceInventoryResponse_Device_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emporiaenergy_partner_api_2_DeviceInventoryResponse_Device_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emporiaenergy_partner_api_2_DeviceInventoryResponse_Device_CircuitInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emporiaenergy_partner_api_2_DeviceInventoryResponse_Device_CircuitInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emporiaenergy_partner_api_2_DeviceInventoryResponse_Device_CustomerInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emporiaenergy_partner_api_2_DeviceInventoryResponse_Device_CustomerInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emporiaenergy_partner_api_2_DeviceUsageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emporiaenergy_partner_api_2_DeviceUsageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emporiaenergy_partner_api_2_DeviceUsageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emporiaenergy_partner_api_2_DeviceUsageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emporiaenergy_partner_api_2_DeviceUsageResponse_DeviceUsage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emporiaenergy_partner_api_2_DeviceUsageResponse_DeviceUsage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emporiaenergy_partner_api_2_DeviceUsageResponse_DeviceUsage_ChannelUsageData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emporiaenergy_partner_api_2_DeviceUsageResponse_DeviceUsage_ChannelUsageData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emporiaenergy_partner_api_2_ListDevicesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emporiaenergy_partner_api_2_ListDevicesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emporiaenergy_partner_api_2_UtilityConnectsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emporiaenergy_partner_api_2_UtilityConnectsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emporiaenergy_partner_api_2_UtilityConnect_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emporiaenergy_partner_api_2_UtilityConnect_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emporiaenergy_partner_api_2_OutletsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emporiaenergy_partner_api_2_OutletsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emporiaenergy_partner_api_2_OutletSettings_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emporiaenergy_partner_api_2_OutletSettings_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emporiaenergy_partner_api_2_UpdateOutletsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emporiaenergy_partner_api_2_UpdateOutletsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emporiaenergy_partner_api_2_EVChargersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emporiaenergy_partner_api_2_EVChargersResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emporiaenergy_partner_api_2_EVCharger_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emporiaenergy_partner_api_2_EVCharger_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emporiaenergy_partner_api_2_UpdateEVChargersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emporiaenergy_partner_api_2_UpdateEVChargersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emporiaenergy_partner_api_2_EVChargerSettings_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emporiaenergy_partner_api_2_EVChargerSettings_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emporiaenergy_partner_api_2_BatteriesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emporiaenergy_partner_api_2_BatteriesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emporiaenergy_partner_api_2_Battery_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emporiaenergy_partner_api_2_Battery_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emporiaenergy_partner_api_2_UpdateBatteriesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emporiaenergy_partner_api_2_UpdateBatteriesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emporiaenergy_partner_api_2_BatterySettings_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emporiaenergy_partner_api_2_BatterySettings_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emporiaenergy_partner_api_2_BatterySettings_LoadFollowing_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emporiaenergy_partner_api_2_BatterySettings_LoadFollowing_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emporiaenergy_partner_api_2_BatterySettings_ChargeWithExcessSolar_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emporiaenergy_partner_api_2_BatterySettings_ChargeWithExcessSolar_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emporiaenergy_partner_api_2_BatterySettings_ChargeToStateOfCharge_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emporiaenergy_partner_api_2_BatterySettings_ChargeToStateOfCharge_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emporiaenergy_partner_api_2_BatterySettings_DischargeToStateOfCharge_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emporiaenergy_partner_api_2_BatterySettings_DischargeToStateOfCharge_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emporiaenergy_partner_api_2_BatterySettings_Idle_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emporiaenergy_partner_api_2_BatterySettings_Idle_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022partner_api2.proto\022\033emporiaenergy.part" +
      "ner_api_2\032\036google/protobuf/wrappers.prot" +
      "o\"@\n\025AuthenticationRequest\022\025\n\rpartner_em" +
      "ail\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\",\n\026Authentic" +
      "ationResponse\022\022\n\nauth_token\030\001 \001(\t\"E\n\026Dev" +
      "iceInventoryRequest\022\022\n\nauth_token\030\001 \001(\t\022" +
      "\027\n\017customer_emails\030\002 \003(\t\"\343\t\n\027DeviceInven" +
      "toryResponse\022L\n\007devices\030\001 \003(\0132;.emporiae" +
      "nergy.partner_api_2.DeviceInventoryRespo" +
      "nse.Device\032\371\010\n\006Device\022\036\n\026manufacturer_de" +
      "vice_id\030\001 \001(\t\022V\n\005model\030\002 \001(\0162G.emporiaen" +
      "ergy.partner_api_2.DeviceInventoryRespon" +
      "se.Device.DeviceModel\022\020\n\010firmware\030\003 \001(\t\022" +
      "\r\n\005solar\030\004 \001(\010\022\020\n\010latitude\030\005 \001(\001\022\021\n\tlong" +
      "itude\030\006 \001(\001\022\023\n\013device_name\030\007 \001(\t\022\020\n\010time" +
      "zone\030\010 \001(\t\022\031\n\rchannel_names\030\t \003(\tB\002\030\001\022\030\n" +
      "\020device_connected\030\n \001(\010\022^\n\rcircuit_infos" +
      "\030\r \003(\0132G.emporiaenergy.partner_api_2.Dev" +
      "iceInventoryResponse.Device.CircuitInfo\022" +
      "[\n\tcustomers\030\014 \003(\0132H.emporiaenergy.partn" +
      "er_api_2.DeviceInventoryResponse.Device." +
      "CustomerInfo\032\333\003\n\013CircuitInfo\022\026\n\016channel_" +
      "number\030\001 \001(\r\022a\n\004type\030\002 \001(\0162S.emporiaener" +
      "gy.partner_api_2.DeviceInventoryResponse" +
      ".Device.CircuitInfo.CircuitType\022q\n\020energ" +
      "y_direction\030\003 \001(\0162W.emporiaenergy.partne" +
      "r_api_2.DeviceInventoryResponse.Device.C" +
      "ircuitInfo.EnergyDirection\022\020\n\010sub_type\030\004" +
      " \001(\t\022\014\n\004name\030\005 \001(\t\"`\n\013CircuitType\022\020\n\014UNK" +
      "NOWN_TYPE\020\000\022\021\n\rVue_200A_Main\020\001\022\025\n\021Vue_50" +
      "A_Expansion\020\002\022\010\n\004Main\020\003\022\013\n\007Battery\020\004\"\\\n\017" +
      "EnergyDirection\022\025\n\021UNKNOWN_DIRECTION\020\000\022\017" +
      "\n\013Consumption\020\001\022\016\n\nGeneration\020\002\022\021\n\rBidir" +
      "ectional\020\003\032D\n\014CustomerInfo\022\022\n\nfirst_name" +
      "\030\001 \001(\t\022\021\n\tlast_name\030\002 \001(\t\022\r\n\005email\030\003 \001(\t" +
      "\"t\n\013DeviceModel\022\013\n\007UNKNOWN\020\000\022\010\n\004Vue1\020\006\022\010" +
      "\n\004Vue2\020\001\022\010\n\004Vue3\020\007\022\022\n\016UtilityConnect\020\002\022\n" +
      "\n\006Outlet\020\003\022\r\n\tEVCharger\020\004\022\013\n\007Battery\020\005\"\261" +
      "\002\n\022DeviceUsageRequest\022\022\n\nauth_token\030\001 \001(" +
      "\t\022\033\n\023start_epoch_seconds\030\002 \001(\004\022\031\n\021end_ep" +
      "och_seconds\030\003 \001(\004\022:\n\005scale\030\004 \001(\0162+.empor" +
      "iaenergy.partner_api_2.DataResolution\022N\n" +
      "\010channels\030\005 \001(\0162<.emporiaenergy.partner_" +
      "api_2.DeviceUsageRequest.UsageChannel\022\037\n" +
      "\027manufacturer_device_ids\030\006 \003(\t\"\"\n\014UsageC" +
      "hannel\022\t\n\005MAINS\020\000\022\007\n\003ALL\020\001\"\220\003\n\023DeviceUsa" +
      "geResponse\022S\n\rdevice_usages\030\001 \003(\0132<.empo" +
      "riaenergy.partner_api_2.DeviceUsageRespo" +
      "nse.DeviceUsage\032\243\002\n\013DeviceUsage\022\036\n\026manuf" +
      "acturer_device_id\030\001 \001(\t\022:\n\005scale\030\002 \001(\0162+" +
      ".emporiaenergy.partner_api_2.DataResolut" +
      "ion\022\034\n\024bucket_epoch_seconds\030\003 \003(\004\022e\n\016cha" +
      "nnel_usages\030\004 \003(\0132M.emporiaenergy.partne" +
      "r_api_2.DeviceUsageResponse.DeviceUsage." +
      "ChannelUsageData\0323\n\020ChannelUsageData\022\017\n\007" +
      "channel\030\001 \001(\r\022\016\n\006usages\030\002 \003(\001\"I\n\022ListDev" +
      "icesRequest\022\022\n\nauth_token\030\001 \001(\t\022\037\n\027manuf" +
      "acturer_device_ids\030\002 \003(\t\"`\n\027UtilityConne" +
      "ctsResponse\022E\n\020utility_connects\030\001 \003(\0132+." +
      "emporiaenergy.partner_api_2.UtilityConne" +
      "ct\"D\n\016UtilityConnect\022\036\n\026manufacturer_dev" +
      "ice_id\030\001 \001(\t\022\022\n\nzigbee_mac\030\014 \001(\t\"O\n\017Outl" +
      "etsResponse\022<\n\007outlets\030\001 \003(\0132+.emporiaen" +
      "ergy.partner_api_2.OutletSettings\"<\n\016Out" +
      "letSettings\022\036\n\026manufacturer_device_id\030\001 " +
      "\001(\t\022\n\n\002on\030\002 \001(\010\"h\n\024UpdateOutletsRequest\022" +
      "\022\n\nauth_token\030\001 \001(\t\022<\n\007outlets\030\002 \003(\0132+.e" +
      "mporiaenergy.partner_api_2.OutletSetting" +
      "s\"P\n\022EVChargersResponse\022:\n\nevchargers\030\001 " +
      "\003(\0132&.emporiaenergy.partner_api_2.EVChar" +
      "ger\"\230\001\n\tEVCharger\022\025\n\rcar_connected\030\001 \001(\010" +
      "\022\024\n\014car_charging\030\002 \001(\010\022\034\n\024max_charge_rat" +
      "e_amps\030\003 \001(\r\022@\n\010settings\030\n \001(\0132..emporia" +
      "energy.partner_api_2.EVChargerSettings\"o" +
      "\n\027UpdateEVChargersRequest\022\022\n\nauth_token\030" +
      "\001 \001(\t\022@\n\010settings\030\002 \003(\0132..emporiaenergy." +
      "partner_api_2.EVChargerSettings\"\223\001\n\021EVCh" +
      "argerSettings\022\036\n\026manufacturer_device_id\030" +
      "\001 \001(\t\022&\n\002on\030\002 \001(\0132\032.google.protobuf.Bool" +
      "Value\0226\n\020charge_rate_amps\030\003 \001(\0132\034.google" +
      ".protobuf.UInt32Value\"L\n\021BatteriesRespon" +
      "se\0227\n\tbatteries\030\001 \003(\0132$.emporiaenergy.pa" +
      "rtner_api_2.Battery\"\271\001\n\007Battery\022\025\n\rcapac" +
      "ity_kwhs\030\001 \001(\001\022!\n\031inverter_max_power_kwa" +
      "tts\030\002 \001(\001\0224\n\016soc_percentage\030\003 \001(\0132\034.goog" +
      "le.protobuf.DoubleValue\022>\n\010settings\030\n \001(" +
      "\0132,.emporiaenergy.partner_api_2.BatteryS" +
      "ettings\"l\n\026UpdateBatteriesRequest\022\022\n\naut" +
      "h_token\030\001 \001(\t\022>\n\010settings\030\002 \003(\0132,.empori" +
      "aenergy.partner_api_2.BatterySettings\"\226\010" +
      "\n\017BatterySettings\022\036\n\026manufacturer_device" +
      "_id\030\001 \001(\t\022<\n\026reserve_soc_percentage\030\002 \001(" +
      "\0132\034.google.protobuf.DoubleValue\022T\n\016load_" +
      "following\030\n \001(\0132:.emporiaenergy.partner_" +
      "api_2.BatterySettings.LoadFollowingH\000\022f\n" +
      "\030charge_with_excess_solar\030\013 \001(\0132B.empori" +
      "aenergy.partner_api_2.BatterySettings.Ch" +
      "argeWithExcessSolarH\000\022g\n\031charge_to_state" +
      "_of_charge\030\014 \001(\0132B.emporiaenergy.partner" +
      "_api_2.BatterySettings.ChargeToStateOfCh" +
      "argeH\000\022m\n\034discharge_to_state_of_charge\030\r" +
      " \001(\0132E.emporiaenergy.partner_api_2.Batte" +
      "rySettings.DischargeToStateOfChargeH\000\022A\n" +
      "\004idle\030\016 \001(\01321.emporiaenergy.partner_api_" +
      "2.BatterySettings.IdleH\000\032C\n\rLoadFollowin" +
      "g\0222\n\014power_kwatts\030\001 \001(\0132\034.google.protobu" +
      "f.DoubleValue\032R\n\025ChargeWithExcessSolar\0229" +
      "\n\023charge_power_kwatts\030\001 \001(\0132\034.google.pro" +
      "tobuf.DoubleValue\032\210\001\n\025ChargeToStateOfCha" +
      "rge\0224\n\016soc_percentage\030\001 \001(\0132\034.google.pro" +
      "tobuf.DoubleValue\0229\n\023charge_power_kwatts" +
      "\030\002 \001(\0132\034.google.protobuf.DoubleValue\032\216\001\n" +
      "\030DischargeToStateOfCharge\0224\n\016soc_percent" +
      "age\030\001 \001(\0132\034.google.protobuf.DoubleValue\022" +
      "<\n\026discharge_power_kwatts\030\002 \001(\0132\034.google" +
      ".protobuf.DoubleValue\032\006\n\004IdleB\017\n\rdispatc" +
      "h_mode*h\n\016DataResolution\022\013\n\007Minutes\020\000\022\022\n" +
      "\016FifteenMinutes\020\001\022\t\n\005Hours\020\002\022\010\n\004Days\020\003\022\t" +
      "\n\005Weeks\020\004\022\n\n\006Months\020\005\022\t\n\005Years\020\0062\250\t\n\nPar" +
      "tnerApi\022w\n\014Authenticate\0222.emporiaenergy." +
      "partner_api_2.AuthenticationRequest\0323.em" +
      "poriaenergy.partner_api_2.Authentication" +
      "Response\022w\n\nGetDevices\0223.emporiaenergy.p" +
      "artner_api_2.DeviceInventoryRequest\0324.em" +
      "poriaenergy.partner_api_2.DeviceInventor" +
      "yResponse\022q\n\014GetUsageData\022/.emporiaenerg" +
      "y.partner_api_2.DeviceUsageRequest\0320.emp" +
      "oriaenergy.partner_api_2.DeviceUsageResp" +
      "onse\022|\n\023ListUtilityConnects\022/.emporiaene" +
      "rgy.partner_api_2.ListDevicesRequest\0324.e" +
      "mporiaenergy.partner_api_2.UtilityConnec" +
      "tsResponse\022l\n\013ListOutlets\022/.emporiaenerg" +
      "y.partner_api_2.ListDevicesRequest\032,.emp" +
      "oriaenergy.partner_api_2.OutletsResponse" +
      "\022p\n\rUpdateOutlets\0221.emporiaenergy.partne" +
      "r_api_2.UpdateOutletsRequest\032,.emporiaen" +
      "ergy.partner_api_2.OutletsResponse\022r\n\016Li" +
      "stEVChargers\022/.emporiaenergy.partner_api" +
      "_2.ListDevicesRequest\032/.emporiaenergy.pa" +
      "rtner_api_2.EVChargersResponse\022y\n\020Update" +
      "EVChargers\0224.emporiaenergy.partner_api_2" +
      ".UpdateEVChargersRequest\032/.emporiaenergy" +
      ".partner_api_2.EVChargersResponse\022p\n\rLis" +
      "tBatteries\022/.emporiaenergy.partner_api_2" +
      ".ListDevicesRequest\032..emporiaenergy.part" +
      "ner_api_2.BatteriesResponse\022v\n\017UpdateBat" +
      "teries\0223.emporiaenergy.partner_api_2.Upd" +
      "ateBatteriesRequest\032..emporiaenergy.part" +
      "ner_api_2.BatteriesResponseB.\n\035com.empor" +
      "iaenergy.partnerapi2B\013PartnerApi2P\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_emporiaenergy_partner_api_2_AuthenticationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_emporiaenergy_partner_api_2_AuthenticationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emporiaenergy_partner_api_2_AuthenticationRequest_descriptor,
        new java.lang.String[] { "PartnerEmail", "Password", });
    internal_static_emporiaenergy_partner_api_2_AuthenticationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_emporiaenergy_partner_api_2_AuthenticationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emporiaenergy_partner_api_2_AuthenticationResponse_descriptor,
        new java.lang.String[] { "AuthToken", });
    internal_static_emporiaenergy_partner_api_2_DeviceInventoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_emporiaenergy_partner_api_2_DeviceInventoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emporiaenergy_partner_api_2_DeviceInventoryRequest_descriptor,
        new java.lang.String[] { "AuthToken", "CustomerEmails", });
    internal_static_emporiaenergy_partner_api_2_DeviceInventoryResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_emporiaenergy_partner_api_2_DeviceInventoryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emporiaenergy_partner_api_2_DeviceInventoryResponse_descriptor,
        new java.lang.String[] { "Devices", });
    internal_static_emporiaenergy_partner_api_2_DeviceInventoryResponse_Device_descriptor =
      internal_static_emporiaenergy_partner_api_2_DeviceInventoryResponse_descriptor.getNestedTypes().get(0);
    internal_static_emporiaenergy_partner_api_2_DeviceInventoryResponse_Device_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emporiaenergy_partner_api_2_DeviceInventoryResponse_Device_descriptor,
        new java.lang.String[] { "ManufacturerDeviceId", "Model", "Firmware", "Solar", "Latitude", "Longitude", "DeviceName", "Timezone", "ChannelNames", "DeviceConnected", "CircuitInfos", "Customers", });
    internal_static_emporiaenergy_partner_api_2_DeviceInventoryResponse_Device_CircuitInfo_descriptor =
      internal_static_emporiaenergy_partner_api_2_DeviceInventoryResponse_Device_descriptor.getNestedTypes().get(0);
    internal_static_emporiaenergy_partner_api_2_DeviceInventoryResponse_Device_CircuitInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emporiaenergy_partner_api_2_DeviceInventoryResponse_Device_CircuitInfo_descriptor,
        new java.lang.String[] { "ChannelNumber", "Type", "EnergyDirection", "SubType", "Name", });
    internal_static_emporiaenergy_partner_api_2_DeviceInventoryResponse_Device_CustomerInfo_descriptor =
      internal_static_emporiaenergy_partner_api_2_DeviceInventoryResponse_Device_descriptor.getNestedTypes().get(1);
    internal_static_emporiaenergy_partner_api_2_DeviceInventoryResponse_Device_CustomerInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emporiaenergy_partner_api_2_DeviceInventoryResponse_Device_CustomerInfo_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Email", });
    internal_static_emporiaenergy_partner_api_2_DeviceUsageRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_emporiaenergy_partner_api_2_DeviceUsageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emporiaenergy_partner_api_2_DeviceUsageRequest_descriptor,
        new java.lang.String[] { "AuthToken", "StartEpochSeconds", "EndEpochSeconds", "Scale", "Channels", "ManufacturerDeviceIds", });
    internal_static_emporiaenergy_partner_api_2_DeviceUsageResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_emporiaenergy_partner_api_2_DeviceUsageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emporiaenergy_partner_api_2_DeviceUsageResponse_descriptor,
        new java.lang.String[] { "DeviceUsages", });
    internal_static_emporiaenergy_partner_api_2_DeviceUsageResponse_DeviceUsage_descriptor =
      internal_static_emporiaenergy_partner_api_2_DeviceUsageResponse_descriptor.getNestedTypes().get(0);
    internal_static_emporiaenergy_partner_api_2_DeviceUsageResponse_DeviceUsage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emporiaenergy_partner_api_2_DeviceUsageResponse_DeviceUsage_descriptor,
        new java.lang.String[] { "ManufacturerDeviceId", "Scale", "BucketEpochSeconds", "ChannelUsages", });
    internal_static_emporiaenergy_partner_api_2_DeviceUsageResponse_DeviceUsage_ChannelUsageData_descriptor =
      internal_static_emporiaenergy_partner_api_2_DeviceUsageResponse_DeviceUsage_descriptor.getNestedTypes().get(0);
    internal_static_emporiaenergy_partner_api_2_DeviceUsageResponse_DeviceUsage_ChannelUsageData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emporiaenergy_partner_api_2_DeviceUsageResponse_DeviceUsage_ChannelUsageData_descriptor,
        new java.lang.String[] { "Channel", "Usages", });
    internal_static_emporiaenergy_partner_api_2_ListDevicesRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_emporiaenergy_partner_api_2_ListDevicesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emporiaenergy_partner_api_2_ListDevicesRequest_descriptor,
        new java.lang.String[] { "AuthToken", "ManufacturerDeviceIds", });
    internal_static_emporiaenergy_partner_api_2_UtilityConnectsResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_emporiaenergy_partner_api_2_UtilityConnectsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emporiaenergy_partner_api_2_UtilityConnectsResponse_descriptor,
        new java.lang.String[] { "UtilityConnects", });
    internal_static_emporiaenergy_partner_api_2_UtilityConnect_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_emporiaenergy_partner_api_2_UtilityConnect_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emporiaenergy_partner_api_2_UtilityConnect_descriptor,
        new java.lang.String[] { "ManufacturerDeviceId", "ZigbeeMac", });
    internal_static_emporiaenergy_partner_api_2_OutletsResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_emporiaenergy_partner_api_2_OutletsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emporiaenergy_partner_api_2_OutletsResponse_descriptor,
        new java.lang.String[] { "Outlets", });
    internal_static_emporiaenergy_partner_api_2_OutletSettings_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_emporiaenergy_partner_api_2_OutletSettings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emporiaenergy_partner_api_2_OutletSettings_descriptor,
        new java.lang.String[] { "ManufacturerDeviceId", "On", });
    internal_static_emporiaenergy_partner_api_2_UpdateOutletsRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_emporiaenergy_partner_api_2_UpdateOutletsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emporiaenergy_partner_api_2_UpdateOutletsRequest_descriptor,
        new java.lang.String[] { "AuthToken", "Outlets", });
    internal_static_emporiaenergy_partner_api_2_EVChargersResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_emporiaenergy_partner_api_2_EVChargersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emporiaenergy_partner_api_2_EVChargersResponse_descriptor,
        new java.lang.String[] { "Evchargers", });
    internal_static_emporiaenergy_partner_api_2_EVCharger_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_emporiaenergy_partner_api_2_EVCharger_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emporiaenergy_partner_api_2_EVCharger_descriptor,
        new java.lang.String[] { "CarConnected", "CarCharging", "MaxChargeRateAmps", "Settings", });
    internal_static_emporiaenergy_partner_api_2_UpdateEVChargersRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_emporiaenergy_partner_api_2_UpdateEVChargersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emporiaenergy_partner_api_2_UpdateEVChargersRequest_descriptor,
        new java.lang.String[] { "AuthToken", "Settings", });
    internal_static_emporiaenergy_partner_api_2_EVChargerSettings_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_emporiaenergy_partner_api_2_EVChargerSettings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emporiaenergy_partner_api_2_EVChargerSettings_descriptor,
        new java.lang.String[] { "ManufacturerDeviceId", "On", "ChargeRateAmps", });
    internal_static_emporiaenergy_partner_api_2_BatteriesResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_emporiaenergy_partner_api_2_BatteriesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emporiaenergy_partner_api_2_BatteriesResponse_descriptor,
        new java.lang.String[] { "Batteries", });
    internal_static_emporiaenergy_partner_api_2_Battery_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_emporiaenergy_partner_api_2_Battery_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emporiaenergy_partner_api_2_Battery_descriptor,
        new java.lang.String[] { "CapacityKwhs", "InverterMaxPowerKwatts", "SocPercentage", "Settings", });
    internal_static_emporiaenergy_partner_api_2_UpdateBatteriesRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_emporiaenergy_partner_api_2_UpdateBatteriesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emporiaenergy_partner_api_2_UpdateBatteriesRequest_descriptor,
        new java.lang.String[] { "AuthToken", "Settings", });
    internal_static_emporiaenergy_partner_api_2_BatterySettings_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_emporiaenergy_partner_api_2_BatterySettings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emporiaenergy_partner_api_2_BatterySettings_descriptor,
        new java.lang.String[] { "ManufacturerDeviceId", "ReserveSocPercentage", "LoadFollowing", "ChargeWithExcessSolar", "ChargeToStateOfCharge", "DischargeToStateOfCharge", "Idle", "DispatchMode", });
    internal_static_emporiaenergy_partner_api_2_BatterySettings_LoadFollowing_descriptor =
      internal_static_emporiaenergy_partner_api_2_BatterySettings_descriptor.getNestedTypes().get(0);
    internal_static_emporiaenergy_partner_api_2_BatterySettings_LoadFollowing_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emporiaenergy_partner_api_2_BatterySettings_LoadFollowing_descriptor,
        new java.lang.String[] { "PowerKwatts", });
    internal_static_emporiaenergy_partner_api_2_BatterySettings_ChargeWithExcessSolar_descriptor =
      internal_static_emporiaenergy_partner_api_2_BatterySettings_descriptor.getNestedTypes().get(1);
    internal_static_emporiaenergy_partner_api_2_BatterySettings_ChargeWithExcessSolar_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emporiaenergy_partner_api_2_BatterySettings_ChargeWithExcessSolar_descriptor,
        new java.lang.String[] { "ChargePowerKwatts", });
    internal_static_emporiaenergy_partner_api_2_BatterySettings_ChargeToStateOfCharge_descriptor =
      internal_static_emporiaenergy_partner_api_2_BatterySettings_descriptor.getNestedTypes().get(2);
    internal_static_emporiaenergy_partner_api_2_BatterySettings_ChargeToStateOfCharge_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emporiaenergy_partner_api_2_BatterySettings_ChargeToStateOfCharge_descriptor,
        new java.lang.String[] { "SocPercentage", "ChargePowerKwatts", });
    internal_static_emporiaenergy_partner_api_2_BatterySettings_DischargeToStateOfCharge_descriptor =
      internal_static_emporiaenergy_partner_api_2_BatterySettings_descriptor.getNestedTypes().get(3);
    internal_static_emporiaenergy_partner_api_2_BatterySettings_DischargeToStateOfCharge_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emporiaenergy_partner_api_2_BatterySettings_DischargeToStateOfCharge_descriptor,
        new java.lang.String[] { "SocPercentage", "DischargePowerKwatts", });
    internal_static_emporiaenergy_partner_api_2_BatterySettings_Idle_descriptor =
      internal_static_emporiaenergy_partner_api_2_BatterySettings_descriptor.getNestedTypes().get(4);
    internal_static_emporiaenergy_partner_api_2_BatterySettings_Idle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emporiaenergy_partner_api_2_BatterySettings_Idle_descriptor,
        new java.lang.String[] { });
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
