// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partner_api2.proto

package com.emporiaenergy.partnerapi2;

public interface UpdateEVChargersRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:emporiaenergy.partner_api_2.UpdateEVChargersRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string auth_token = 1;</code>
   * @return The authToken.
   */
  java.lang.String getAuthToken();
  /**
   * <code>string auth_token = 1;</code>
   * @return The bytes for authToken.
   */
  com.google.protobuf.ByteString
      getAuthTokenBytes();

  /**
   * <pre>
   * one or more ev chargers to update; the caller must set at least one of the changeable fields in each EVChargerSettings.  
   * </pre>
   *
   * <code>repeated .emporiaenergy.partner_api_2.EVChargerSettings settings = 2;</code>
   */
  java.util.List<com.emporiaenergy.partnerapi2.EVChargerSettings> 
      getSettingsList();
  /**
   * <pre>
   * one or more ev chargers to update; the caller must set at least one of the changeable fields in each EVChargerSettings.  
   * </pre>
   *
   * <code>repeated .emporiaenergy.partner_api_2.EVChargerSettings settings = 2;</code>
   */
  com.emporiaenergy.partnerapi2.EVChargerSettings getSettings(int index);
  /**
   * <pre>
   * one or more ev chargers to update; the caller must set at least one of the changeable fields in each EVChargerSettings.  
   * </pre>
   *
   * <code>repeated .emporiaenergy.partner_api_2.EVChargerSettings settings = 2;</code>
   */
  int getSettingsCount();
  /**
   * <pre>
   * one or more ev chargers to update; the caller must set at least one of the changeable fields in each EVChargerSettings.  
   * </pre>
   *
   * <code>repeated .emporiaenergy.partner_api_2.EVChargerSettings settings = 2;</code>
   */
  java.util.List<? extends com.emporiaenergy.partnerapi2.EVChargerSettingsOrBuilder> 
      getSettingsOrBuilderList();
  /**
   * <pre>
   * one or more ev chargers to update; the caller must set at least one of the changeable fields in each EVChargerSettings.  
   * </pre>
   *
   * <code>repeated .emporiaenergy.partner_api_2.EVChargerSettings settings = 2;</code>
   */
  com.emporiaenergy.partnerapi2.EVChargerSettingsOrBuilder getSettingsOrBuilder(
      int index);
}
