// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partner_api2.proto

package com.emporiaenergy.partnerapi2;

public interface UtilityConnectsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:emporiaenergy.partner_api_2.UtilityConnectsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .emporiaenergy.partner_api_2.UtilityConnect utility_connects = 1;</code>
   */
  java.util.List<com.emporiaenergy.partnerapi2.UtilityConnect> 
      getUtilityConnectsList();
  /**
   * <code>repeated .emporiaenergy.partner_api_2.UtilityConnect utility_connects = 1;</code>
   */
  com.emporiaenergy.partnerapi2.UtilityConnect getUtilityConnects(int index);
  /**
   * <code>repeated .emporiaenergy.partner_api_2.UtilityConnect utility_connects = 1;</code>
   */
  int getUtilityConnectsCount();
  /**
   * <code>repeated .emporiaenergy.partner_api_2.UtilityConnect utility_connects = 1;</code>
   */
  java.util.List<? extends com.emporiaenergy.partnerapi2.UtilityConnectOrBuilder> 
      getUtilityConnectsOrBuilderList();
  /**
   * <code>repeated .emporiaenergy.partner_api_2.UtilityConnect utility_connects = 1;</code>
   */
  com.emporiaenergy.partnerapi2.UtilityConnectOrBuilder getUtilityConnectsOrBuilder(
      int index);
}
