// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partner_api2.proto

package com.emporiaenergy.partnerapi2;

/**
 * <pre>
 ** Describes a Utility Connect (Emporia device that connects to an AMI Smart Meter using the Zigbee protocol) 
 * </pre>
 *
 * Protobuf type {@code emporiaenergy.partner_api_2.UtilityConnect}
 */
public final class UtilityConnect extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:emporiaenergy.partner_api_2.UtilityConnect)
    UtilityConnectOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UtilityConnect.newBuilder() to construct.
  private UtilityConnect(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UtilityConnect() {
    manufacturerDeviceId_ = "";
    zigbeeMac_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UtilityConnect();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UtilityConnect(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            manufacturerDeviceId_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            zigbeeMac_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.emporiaenergy.partnerapi2.PartnerApi2.internal_static_emporiaenergy_partner_api_2_UtilityConnect_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.emporiaenergy.partnerapi2.PartnerApi2.internal_static_emporiaenergy_partner_api_2_UtilityConnect_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.emporiaenergy.partnerapi2.UtilityConnect.class, com.emporiaenergy.partnerapi2.UtilityConnect.Builder.class);
  }

  public static final int MANUFACTURER_DEVICE_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object manufacturerDeviceId_;
  /**
   * <code>string manufacturer_device_id = 1;</code>
   * @return The manufacturerDeviceId.
   */
  @java.lang.Override
  public java.lang.String getManufacturerDeviceId() {
    java.lang.Object ref = manufacturerDeviceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      manufacturerDeviceId_ = s;
      return s;
    }
  }
  /**
   * <code>string manufacturer_device_id = 1;</code>
   * @return The bytes for manufacturerDeviceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getManufacturerDeviceIdBytes() {
    java.lang.Object ref = manufacturerDeviceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      manufacturerDeviceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ZIGBEE_MAC_FIELD_NUMBER = 12;
  private volatile java.lang.Object zigbeeMac_;
  /**
   * <pre>
   ** the MAC of the Zigbee radio, which will be unavailable if the device hasn't connected to Emporia's cloud yet 
   * </pre>
   *
   * <code>string zigbee_mac = 12;</code>
   * @return The zigbeeMac.
   */
  @java.lang.Override
  public java.lang.String getZigbeeMac() {
    java.lang.Object ref = zigbeeMac_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      zigbeeMac_ = s;
      return s;
    }
  }
  /**
   * <pre>
   ** the MAC of the Zigbee radio, which will be unavailable if the device hasn't connected to Emporia's cloud yet 
   * </pre>
   *
   * <code>string zigbee_mac = 12;</code>
   * @return The bytes for zigbeeMac.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getZigbeeMacBytes() {
    java.lang.Object ref = zigbeeMac_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      zigbeeMac_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getManufacturerDeviceIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, manufacturerDeviceId_);
    }
    if (!getZigbeeMacBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, zigbeeMac_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getManufacturerDeviceIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, manufacturerDeviceId_);
    }
    if (!getZigbeeMacBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, zigbeeMac_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.emporiaenergy.partnerapi2.UtilityConnect)) {
      return super.equals(obj);
    }
    com.emporiaenergy.partnerapi2.UtilityConnect other = (com.emporiaenergy.partnerapi2.UtilityConnect) obj;

    if (!getManufacturerDeviceId()
        .equals(other.getManufacturerDeviceId())) return false;
    if (!getZigbeeMac()
        .equals(other.getZigbeeMac())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MANUFACTURER_DEVICE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getManufacturerDeviceId().hashCode();
    hash = (37 * hash) + ZIGBEE_MAC_FIELD_NUMBER;
    hash = (53 * hash) + getZigbeeMac().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.emporiaenergy.partnerapi2.UtilityConnect parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.emporiaenergy.partnerapi2.UtilityConnect parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.emporiaenergy.partnerapi2.UtilityConnect parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.emporiaenergy.partnerapi2.UtilityConnect parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.emporiaenergy.partnerapi2.UtilityConnect parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.emporiaenergy.partnerapi2.UtilityConnect parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.emporiaenergy.partnerapi2.UtilityConnect parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.emporiaenergy.partnerapi2.UtilityConnect parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.emporiaenergy.partnerapi2.UtilityConnect parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.emporiaenergy.partnerapi2.UtilityConnect parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.emporiaenergy.partnerapi2.UtilityConnect parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.emporiaenergy.partnerapi2.UtilityConnect parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.emporiaenergy.partnerapi2.UtilityConnect prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   ** Describes a Utility Connect (Emporia device that connects to an AMI Smart Meter using the Zigbee protocol) 
   * </pre>
   *
   * Protobuf type {@code emporiaenergy.partner_api_2.UtilityConnect}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:emporiaenergy.partner_api_2.UtilityConnect)
      com.emporiaenergy.partnerapi2.UtilityConnectOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.emporiaenergy.partnerapi2.PartnerApi2.internal_static_emporiaenergy_partner_api_2_UtilityConnect_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.emporiaenergy.partnerapi2.PartnerApi2.internal_static_emporiaenergy_partner_api_2_UtilityConnect_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.emporiaenergy.partnerapi2.UtilityConnect.class, com.emporiaenergy.partnerapi2.UtilityConnect.Builder.class);
    }

    // Construct using com.emporiaenergy.partnerapi2.UtilityConnect.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      manufacturerDeviceId_ = "";

      zigbeeMac_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.emporiaenergy.partnerapi2.PartnerApi2.internal_static_emporiaenergy_partner_api_2_UtilityConnect_descriptor;
    }

    @java.lang.Override
    public com.emporiaenergy.partnerapi2.UtilityConnect getDefaultInstanceForType() {
      return com.emporiaenergy.partnerapi2.UtilityConnect.getDefaultInstance();
    }

    @java.lang.Override
    public com.emporiaenergy.partnerapi2.UtilityConnect build() {
      com.emporiaenergy.partnerapi2.UtilityConnect result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.emporiaenergy.partnerapi2.UtilityConnect buildPartial() {
      com.emporiaenergy.partnerapi2.UtilityConnect result = new com.emporiaenergy.partnerapi2.UtilityConnect(this);
      result.manufacturerDeviceId_ = manufacturerDeviceId_;
      result.zigbeeMac_ = zigbeeMac_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.emporiaenergy.partnerapi2.UtilityConnect) {
        return mergeFrom((com.emporiaenergy.partnerapi2.UtilityConnect)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.emporiaenergy.partnerapi2.UtilityConnect other) {
      if (other == com.emporiaenergy.partnerapi2.UtilityConnect.getDefaultInstance()) return this;
      if (!other.getManufacturerDeviceId().isEmpty()) {
        manufacturerDeviceId_ = other.manufacturerDeviceId_;
        onChanged();
      }
      if (!other.getZigbeeMac().isEmpty()) {
        zigbeeMac_ = other.zigbeeMac_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.emporiaenergy.partnerapi2.UtilityConnect parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.emporiaenergy.partnerapi2.UtilityConnect) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object manufacturerDeviceId_ = "";
    /**
     * <code>string manufacturer_device_id = 1;</code>
     * @return The manufacturerDeviceId.
     */
    public java.lang.String getManufacturerDeviceId() {
      java.lang.Object ref = manufacturerDeviceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        manufacturerDeviceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string manufacturer_device_id = 1;</code>
     * @return The bytes for manufacturerDeviceId.
     */
    public com.google.protobuf.ByteString
        getManufacturerDeviceIdBytes() {
      java.lang.Object ref = manufacturerDeviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        manufacturerDeviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string manufacturer_device_id = 1;</code>
     * @param value The manufacturerDeviceId to set.
     * @return This builder for chaining.
     */
    public Builder setManufacturerDeviceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      manufacturerDeviceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string manufacturer_device_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearManufacturerDeviceId() {
      
      manufacturerDeviceId_ = getDefaultInstance().getManufacturerDeviceId();
      onChanged();
      return this;
    }
    /**
     * <code>string manufacturer_device_id = 1;</code>
     * @param value The bytes for manufacturerDeviceId to set.
     * @return This builder for chaining.
     */
    public Builder setManufacturerDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      manufacturerDeviceId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object zigbeeMac_ = "";
    /**
     * <pre>
     ** the MAC of the Zigbee radio, which will be unavailable if the device hasn't connected to Emporia's cloud yet 
     * </pre>
     *
     * <code>string zigbee_mac = 12;</code>
     * @return The zigbeeMac.
     */
    public java.lang.String getZigbeeMac() {
      java.lang.Object ref = zigbeeMac_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        zigbeeMac_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     ** the MAC of the Zigbee radio, which will be unavailable if the device hasn't connected to Emporia's cloud yet 
     * </pre>
     *
     * <code>string zigbee_mac = 12;</code>
     * @return The bytes for zigbeeMac.
     */
    public com.google.protobuf.ByteString
        getZigbeeMacBytes() {
      java.lang.Object ref = zigbeeMac_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        zigbeeMac_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     ** the MAC of the Zigbee radio, which will be unavailable if the device hasn't connected to Emporia's cloud yet 
     * </pre>
     *
     * <code>string zigbee_mac = 12;</code>
     * @param value The zigbeeMac to set.
     * @return This builder for chaining.
     */
    public Builder setZigbeeMac(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      zigbeeMac_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     ** the MAC of the Zigbee radio, which will be unavailable if the device hasn't connected to Emporia's cloud yet 
     * </pre>
     *
     * <code>string zigbee_mac = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearZigbeeMac() {
      
      zigbeeMac_ = getDefaultInstance().getZigbeeMac();
      onChanged();
      return this;
    }
    /**
     * <pre>
     ** the MAC of the Zigbee radio, which will be unavailable if the device hasn't connected to Emporia's cloud yet 
     * </pre>
     *
     * <code>string zigbee_mac = 12;</code>
     * @param value The bytes for zigbeeMac to set.
     * @return This builder for chaining.
     */
    public Builder setZigbeeMacBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      zigbeeMac_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:emporiaenergy.partner_api_2.UtilityConnect)
  }

  // @@protoc_insertion_point(class_scope:emporiaenergy.partner_api_2.UtilityConnect)
  private static final com.emporiaenergy.partnerapi2.UtilityConnect DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.emporiaenergy.partnerapi2.UtilityConnect();
  }

  public static com.emporiaenergy.partnerapi2.UtilityConnect getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UtilityConnect>
      PARSER = new com.google.protobuf.AbstractParser<UtilityConnect>() {
    @java.lang.Override
    public UtilityConnect parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UtilityConnect(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UtilityConnect> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UtilityConnect> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.emporiaenergy.partnerapi2.UtilityConnect getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

